### ISSUE TITLE
add support for streaming video

### ISSUE THREAD

**Issue by tekknikk** [jepiqueau/capacitor-video-player#10]
this player works great for videos from AWS S3.  What would it take to add support for AWS streaming? 

URL example for AWS Streaming
`https://fdhsfhsrfhfgh!!?.data.mediastore.ap-southeast-2.amazonaws.com/p/index.m3u8`

**Comment by tekknikk** [comment]
this works:

`
  ngAfterViewInit() {
    const options = {
      'sources' : [{
        'src' : this.urlVideo,
        'type' : 'application/x-mpegURL'
        }
      ],
      'poster' : this.urlPoster,
      'data-setup': '{"liveui": true}'
    };
    this.vjs = videojs('my-player', options);

  }
`

**Comment by tekknikk** [comment]
``

**Comment by jepiqueau** [comment]
@tekknikk I am not familiar with AWS Streaming can you provide me some references so i can have a look and try to understand.

**Comment by jepiqueau** [comment]
@tekknikk Are you sure that your url is correct i tested with `http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8` and it works well on IOS but not on Android devices

**Comment by jepiqueau** [comment]
@tekknikk you didn't come back to me. I have been looking on exoplayer from google for android but it is not as easy as i can read some network links but not yours and not even the one from apple i referenced earlier. on IOS with the standard player i can read a lot of link but not yours. I have tried also videolan vlc i can read quite a few but not yours. Is AWS Streaming use a special encoding ? and what about the web plugin ?. So which platform are you looking to ?

**Comment by tekknikk** [comment]
Apologies for delay in comms.  Things have been crazy.  The url I gave you was made up.  I will send you a real one now.

**Comment by tekknikk** [comment]
this url works in video.js

https://video-develop-output-annukri9.s3-ap-southeast-2.amazonaws.com/output/3d-print-workshop_Ott_Hls_Ts_Avc_Aac_16x9_1280x720p_30Hz_3500Kbps.m3u8

**Comment by tekknikk** [comment]
i'm using this AWS amplify VOD beta plugin

<img width="744" alt="Screen Shot 2020-05-03 at 12 31 40 AM" src="https://user-images.githubusercontent.com/18043/80867089-97bead80-8cd5-11ea-80d1-2f5a745c781b.png">

**Comment by tekknikk** [comment]
so i can create templates with available output options:

<img width="624" alt="Screen Shot 2020-05-03 at 12 34 03 AM" src="https://user-images.githubusercontent.com/18043/80867162-f6842700-8cd5-11ea-82e2-451fb4eae030.png">

**Comment by tekknikk** [comment]
Initial output testing indicates:
DASH not playing with error of unknown source
https://tv-develop-output-no9tr3ka.s3-ap-southeast-2.amazonaws.com/creating-an-issue.mpd

CMAF  does play!
**video**
https://tv-develop-output-no9tr3ka.s3-ap-southeast-2.amazonaws.com/creating-an-issuetesting-cmaf.cmfv

**audio**
https://tv-develop-output-no9tr3ka.s3-ap-southeast-2.amazonaws.com/creating-an-issue.cmfa

**Comment by jepiqueau** [comment]
@tekknikk  i have tried 
https://video-develop-output-annukri9.s3-ap-southeast-2.amazonaws.com/output/3d-print-workshop_Ott_Hls_Ts_Avc_Aac_16x9_1280x720p_30Hz_3500Kbps.m3u8
on my development release i can open it on the web, ios, android but it is quite slow to download at the beginning and there is no sound at the beginning till you reach 5'41 is it normal?

Can you try to do for testing a smaller video 10' with sound from beginning and using the Default Encoding Template (Apple HLS @ 1080p30)
In the new release i will try tp propose only HLS, which is already a big effort as i have to completely rewrite the android and web plugin, i will use Hls.js for Web and ExoPlayer for Android. For ios, the native player plays the HLS & CMAF files. On the CMAF file you gave there is no sound can you confirm. IOS player does not support DASH so il will not go for that one. Which platform are you targeting first ?

**Comment by tekknikk** [comment]
try this:
https://tv-develop-output-no9tr3ka.s3-ap-southeast-2.amazonaws.com/IMG_2163/IMG_2163.m3u8

**Comment by tekknikk** [comment]
> On the CMAF file you gave there is no sound can you confirm.

Yes. CMAF output has been splitting video and audio as separate files.

**Comment by jepiqueau** [comment]
@tekknikk I had to move from Hls.js to video.js to have the DASH working. The Dash example you gave me doesn't work. but i found some on the net for testing. For my understanding, any reason for splitting the CMAF into video and sound, can you give me an example with only one file. I have know all the bit and pieces to modify the plugin. At the end the Web Plugin will support All formats, IOS will not support DASH and Android will support all formats. I do not know yet how long it will take to get the plugin ready and tested. Thanks to bring me the question, but i had 3 or 4 hard days to try understanding the basics of the technology involved. I am not sure how to let open the setting of the  options for streaming

**Comment by tekknikk** [comment]
@jepiqueau many many thanks for working on this issue. I really appreciate it man and please let me know if there is anything i can do to help. For DASH it seems like the player has difficulty reading an index file for streams ie the *.mpd which then references mp4 files that the current player can play. I think this is the same for the m3u8 index files.

If the video.js version is working ok, can i test it? Could you push the branch you are working on?

**Comment by tekknikk** [comment]
hls.js should support these m3u8 streams...maybe i need to change the way i'm initializing the player?

**Comment by jepiqueau** [comment]
@tekknikk Well, thinks are not going as planned, i cannot integrate in capacitor the part that i tested with video.js, capacitor cannot find the video.js module, something wrong with the @types/video.js which i cannot figure out. i move back now to hls.js to see if i can integrate easily with capacitor. Meaning no DASH files. I let you know later.

**Comment by jepiqueau** [comment]
@tekknikk I am nearly there for Web and IOS plugins. I implemented Hls and Hls fragmented fMp4support. Can you provided me a short CMAF with video and sound that i can use to demonstrate the CMAF support in my angular-video-player-starter and my pwa-video-player-app-starter. I would really appreciate

**Comment by jepiqueau** [comment]
@tekknikk Finally got there for Web & IOS see capacitor-video-player@2.0.1-6, still android to do...
tell me when you have tested it

**Comment by jepiqueau** [comment]
@tekknikk Support for DASH, HLS, ISM has been added to the Android plugin. Hope you will enjoy.

**Comment by jepiqueau** [comment]
@tekknikk has you did not give me feedback, i close the issue

**Comment by tekknikk** [comment]
amazing work @jepiqueau i am super impressed.  thank you sir.

**Comment by jepiqueau** [comment]
Ok you are welcome, that was a good question but hard to solve, i will may be come back to video.js for having access to Dash video, or may be keep using Hls.js and use Dash.js for Dash file. Will see. But to day you have i think something that you can start working with. Thanks again that really enhance capabilities of the plugin, the last thing will be to add a youtube player. I also test it on live video it works well.
