### ISSUE TITLE
I want the video on ios in embedeed mode.

### ISSUE THREAD

**Issue by Web2Integrators** [jepiqueau/capacitor-video-player#102]
I want the video to take the half the height of the Iphone.

Currently video open in full screen mode.

Any plan for embedded mode on ios?

**Comment by jepiqueau** [comment]
@Web2Integrators i would have wish to provide this and have worked hard to do it without success in the past. Capacitor can only present a viewController fullscreen. If you have an idea to do it please feel free to make a PR

**Comment by mugavri** [comment]
any update?

**Comment by jepiqueau** [comment]
@mugavri nothing has changed
