### ISSUE TITLE
Programmatically Exit Player

### ISSUE THREAD

**Issue by mattsputnikdigital** [jepiqueau/capacitor-video-player#103]
Firstly thanks for the plugin!

On iOS / Android I would like to be able to close the video programatically. I would like to do this if the user is logged out in the background for instance.

I have tried stopAllPlayers() but this just seems to pause the video and it stays full screen on iOS.

Is this possible?

**Comment by jepiqueau** [comment]
@mattsputnikdigital first thanks for using the plugin. Exiting the player programatically has not been implemented.
