### ISSUE TITLE
iOS - Swiping Video Off Screen Does Not Destroy The Video

### ISSUE THREAD

**Issue by mattsputnikdigital** [jepiqueau/capacitor-video-player#105]
It seems since iOS 13 you can swipe to close views. If this is done on iOS whilst a video is playing the video is paused but not destroyed. There is no way to get the video back on screen but you can start the video playing again with .play() and only the sound plays.

The event "jeepCapVideoPlayerPause" is fired but instead the event "jeepCapVideoPlayerExit" should be fired and the AV view destroyed.

As a different fix, the swiping behaviour can be disabled web setting ".isModalInPresentation = true" on the AV view controller. This would probably be the best short term fix as people who rely on events are not receiving all/correct ones.

https://www.hackingwithswift.com/example-code/uikit/how-to-disable-interactive-swipe-to-dismiss-for-view-controllers

**Comment by jepiqueau** [comment]
@mattsputnikdigital When you swipe to close view when a video is playing , the video is paused and the application goes in the background. if you open the application again the video will restart to play from where it was paused and so on. This is the normal behavior as requested by many developers. I test it on the iPhone 13 Pro Max simulator and it works well. if you does not want this behavior set the `bkmodeEnabled` to false in the initPlayer options.

**Comment by mattsputnikdigital** [comment]
@jepiqueau you can swipe the video away but the app remains open. You need to touch the video and not any other part of the view. The video shrinks and you can move it around the screen like a little icon. bkmodeEnabled does nothing to solve this.

**Comment by mattsputnikdigital** [comment]
@jepiqueau here is a screen recording of the issue https://www.dropbox.com/s/h4mhsmpnef9r0z8/Screen%20Recording%202022-08-31%20at%2010.48.28.mov?dl=0

You will notice the video closes, fires the pause event, but the app remains open. bkmodeEnabled in this video is set to false, but that setting does not change the behaviour.

**Comment by mattsputnikdigital** [comment]
@jepiqueau here is another recording to show the issue https://www.dropbox.com/s/qkndjabfwwuow23/Screen%20Recording%202022-08-31%20at%2011.05.30.mov?dl=0

PIP and Background Mode are disabled.

Dragging the video towards the top of the screen closed the video and the ended event fires.

Dragging the video towards the bottom of the screen pauses and hides the video and no ended event fires.

If the app is then minimised and reopened the video sound plays, but the video is no longer shown on screen.

**Comment by mattsputnikdigital** [comment]
This page shows the new iOS gestures https://sarunw.com/posts/modality-changes-in-ios13/

**Comment by jepiqueau** [comment]
@mattsputnikdigital What you are showing is dragging the video i thought it was swiping of the view. In that case i reproduced the issue i never thought about this. i will have a look

**Comment by jepiqueau** [comment]
@mattsputnikdigital  i fix the issue which will be part of the next release

if you want to test it makes these changes in `FullScreenVideoPlayerView`  
 - add variable
 - 
```
    var videoPlayerMoveObserver: NSKeyValueObservation?
```
- add in func addObservers at the end

```
        self.videoPlayerMoveObserver = self.videoPlayer
            .observe(\.view.center, options: [.new, .old],
                      changeHandler: {(_, _) in
                if !isInPIPMode {
                    if self.videoPlayer.isBeingDismissed && !isVideoEnded {

                        NotificationCenter.default.post(name: .playerFullscreenDismiss, object: nil)
                    }

                }

            })
```
this is strange that the drag-up, drag-left, drag-right fire the `frame` observer and drag-down fired the `view center` observer. This could be an Apple bug
