### ISSUE TITLE
Bug: app crashes or throws response error 403 with some videos

### ISSUE THREAD

**Issue by PhantomPainX** [jepiqueau/capacitor-video-player#108]
### Error 1 (app crashes)

When I use some video links, the app crashes before the video starts. I traced the error and it happens in this function:

```
private String getVideoType(Uri uri) {
        String ret = null;
        String lastSegment = uri.getLastPathSegment();
        for (String type : supportedFormat) {
            if (ret != null) break;
            if (lastSegment.contains(type)) ret = type;
            if (ret == null) {
                List<String> segments = uri.getPathSegments();
                String segment;
                if (segments.get(segments.size() - 1).equals("manifest")) {
                    segment = segments.get(segments.size() - 2);
                } else {
                    segment = segments.get(segments.size() - 1);
                }
                for (String sType : supportedFormat) {
                    if (segment.contains(sType)) {
                        ret = sType;
                        break;
                    }
                }
            }
        }
        return ret;
    }
```

You can use this link to reproduce the error:  https://vd278.mycdn.me/?expires=1662582616116&srcIp=181.182.87.101&pr=10&srcAg=UNKNOWN_ANDROID&ms=181.222.52.28&type=3&sig=v2xymxzA7As&ct=0&urls=183.226.33.26&clientType=0&zs=43&id=3030515714639

It won't play anything because the link is temporally and restricted to an IP for a limited time, but it will crash the app.

### Error 2 (throws source response error 403)

With some video urls the app throws Error 403, when MediaPlayer plays these same videos perfectly. I think it is an error with the request, maybe user-agent or something.

Again, the example link is temporally and won't work, but if you want a refreshed one, tell me and I can generate one for you to test the issue.

Example:  https://cdn59.my.mail.ru/hv/75143011.mp4?slave%5B%5D=s%253Ahttp%253A%252F%252Fvideo-cephrgw2.i%253A9091%252Fvideo4%252F75143011-hv&p=f&expire_at=1662508800&touch=1662492023&reg=247&sign=d7d6d740b2679e6d581c3bba2ba5e4a23ea13c5a

-----------------------------------------------------------------------------------

Of course I tried to fix those error before write the issue but I didn't have success, so if you have any idea or can fix it I would be very thankful.

**Comment by jepiqueau** [comment]
@PhantomPainX error 1 it could not find the type of the video so it should return null

**Comment by jepiqueau** [comment]
@PhantomPainX do you know which vidéo format is the video

**Comment by jepiqueau** [comment]
@PhantomPainX did this work on iOS

**Comment by PhantomPainX** [comment]
@jepiqueau 

- I don't know the type of the video however I'm investigating it. (It can be mp4 I think)
- Error 1 works in iOS. 403 source error doesn't work in iOS.

**Comment by jepiqueau** [comment]
@PhantomPainX  Can you tell me for case 1 if you change getVideoType by

```java
    private String getVideoType(Uri uri) {
        String ret = null;
        Object obj = uri.getLastPathSegment();
        String lastSegment = (obj == null) ? "" : uri.getLastPathSegment();
        for (String type : supportedFormat) {
            if (ret != null) break;
            if(lastSegment.length() > 0 && lastSegment.contains(type)) ret = type;
            if (ret == null) {
                List<String> segments = uri.getPathSegments();
                if(segments.size() > 0) {
                  String segment;
                  if (segments.get(segments.size() - 1).equals("manifest")) {
                    segment = segments.get(segments.size() - 2);
                  } else {
                    segment = segments.get(segments.size() - 1);
                  }
                  for (String sType : supportedFormat) {
                    if (segment.contains(sType)) {
                      ret = sType;
                      break;
                    }
                  }
                }
            }
        }
        ret = (ret != null) ? ret : "";
        return ret;
    }

```
if you can read the video

**Comment by PhantomPainX** [comment]
> @PhantomPainX Can you tell me for case 1 if you change getVideoType by
> 
> ```java
>     private String getVideoType(Uri uri) {
>         String ret = null;
>         Object obj = uri.getLastPathSegment();
>         String lastSegment = (obj == null) ? "" : uri.getLastPathSegment();
>         for (String type : supportedFormat) {
>             if (ret != null) break;
>             if(lastSegment.length() > 0 && lastSegment.contains(type)) ret = type;
>             if (ret == null) {
>                 List<String> segments = uri.getPathSegments();
>                 if(segments.size() > 0) {
>                   String segment;
>                   if (segments.get(segments.size() - 1).equals("manifest")) {
>                     segment = segments.get(segments.size() - 2);
>                   } else {
>                     segment = segments.get(segments.size() - 1);
>                   }
>                   for (String sType : supportedFormat) {
>                     if (segment.contains(sType)) {
>                       ret = sType;
>                       break;
>                     }
>                   }
>                 }
>             }
>         }
>         ret = (ret != null) ? ret : "";
>         return ret;
>     }
> ```
> 
> if you can read the video

So nice dude!!! it works perfectly now

**Comment by jepiqueau** [comment]
@PhantomPainX OK i will put it in the new release. Is this working on iOS? Do uou still have the error2 or everything works

**Comment by PhantomPainX** [comment]
> @PhantomPainX OK i will put it in the new release. Is this working on iOS? Do uou still have the error2 or everything works

The error 1 is solved for android, iOS never had that problem, however the error 2 persists in both

**Comment by jepiqueau** [comment]
@PhantomPainX for error 2 i will need an access to that vidéo to try understanding. I will not work on this before this evening

**Comment by PhantomPainX** [comment]
@jepiqueau here is the code where the videos can be resolved, basically is the same old code I posted in the other issue topic but with some additions:

mailRuResolver() -> get mp4 videos (uses capacitor http native plugin)

```typescript
import { Component, OnInit } from '@angular/core';

import { CapacitorVideoPlayer } from 'capacitor-video-player';

import { HTTP } from '@awesome-cordova-plugins/http/ngx';

import { Http } from '@capacitor-community/http';

@Component({
  selector: 'app-videos',
  templateUrl: './videos.page.html',
  styleUrls: ['./videos.page.scss'],
})
export class VideosPage implements OnInit {


  private capacitorVideoPlayer: any = CapacitorVideoPlayer;

  private testEmbedUrls: any[string] = [
    "https://fembed.com/v/7zv-jnkg2ox",
    "https://fembed.com/v/3q91j75d29y",
    "https://fembed.com/v/4dvjxzd0y91"
  ]

  private error403urls: any[string] = [
    'https://my.mail.ru/video/embed/9149163570439660295#tioanime#8967',
    'https://my.mail.ru/video/embed/9149163570439659873#tioanime#8545'
  ];

  constructor(private http: HTTP) { }

  ngOnInit() {
    this.playVideo(this.error403urls[0]);
  }

  async playVideo(embedUrl: string) {

    // this.fembedResolver(embedUrl).then((videos) => {
    //   this.nativePlayer2(videos[0], "Title", "smallTitle");
    // });

    this.mailRuResolver(embedUrl).then((videos) => {
      this.nativePlayer2(videos[0], "Title", "smallTitle");
    });
  }

  // With this you get raw videos
  async fembedResolver(url: string) {
    url = url.replace("fembed.com", "vanfem.com");
    url = url.replace("/v/", "/api/source/");

    return new Promise((resolve, reject) => {

      this.http.post(url, {}, {
      'Content-Type': 'application/json',
      'Referer': url
      }).then(data => {
        console.log(data.data);
        const json = JSON.parse(data.data);
        const mVideos = json.data;
        var videos = [];

        mVideos.forEach(video => {
          videos.push({
            'label': video.label,
            'file': video.file,
            'referer': url
          });
        });
        const document = videos;
        resolve(document);
      }).catch(err => {
        reject(err); 
      });
    });
  }

  async nativePlayer2(video: any, title, smallTitle) {

    console.log("URL: ",encodeURI(video.file));
    await this.capacitorVideoPlayer.initPlayer({
      mode: 'fullscreen',
      url: encodeURI(video.file),
      playerId: 'player1',
      headers: {
        Referer: video.referer
      },
      title: title,
      smallTitle: smallTitle,
      accentColor: "#f0b400",
      chromecast: true
    }).then(() => {
      console.log('Player initialized');
      this.capacitorVideoPlayer.play({playerId: 'player1'}).then(() => {
        //this.screenOrientation.lock(this.screenOrientation.ORIENTATIONS.ANY);
        console.log('Player playing');

      }).catch(err => {
        console.log('Error playing', err);
        this.capacitorVideoPlayer.stopAllPlayers().then(() => {
          console.log('All players stopped');
        });
      });
    }).catch(err => {
      console.log('Error initializing player', err);
      this.capacitorVideoPlayer.stopAllPlayers().then(() => {
        console.log('All players stopped');
      });
    });
    
    await this.capacitorVideoPlayer.addListener('jeepCapVideoPlayerExit', (data) => {
      console.log('Player exited');
      //this.screenOrientation.lock(this.screenOrientation.ORIENTATIONS.PORTRAIT);
    });

    await this.capacitorVideoPlayer.addListener('jeepCapVideoPlayerEnded', (data) => {
      console.log('Player ended');
      //this.screenOrientation.lock(this.screenOrientation.ORIENTATIONS.PORTRAIT);
    });
  }


  async mailRuResolver(url: string) {
    return new Promise((resolve, reject) => {

      let urlFix = url.replace('https://my.mail.ru/video/embed/', '');
      urlFix = urlFix.substring(0, urlFix.indexOf('#'));
      const final_url = "https://my.mail.ru/+/video/meta/" + urlFix;

      const options = {
        url: final_url
      };
      
      Http.get(options).then(data => {
        const json = data.data;
        let videos = [];
        json.videos.forEach(video => {
          videos.push({
            'label': video.key,
            'file': "https://" + video.url.substring(2),//delete the first two characters of url and add https://
            'referer': url
          });
        });

        const document = videos;
        resolve(document);
      }).catch(err => {
        reject(err);
      });
    });
  }

}
```

It should work for you to test the issue, if there's a problem tell me

**Comment by jepiqueau** [comment]
@PhantomPainX if i play 
```
    const url = `https://cdn32.my.mail.ru/v/75148598.mp4?slave[]=s%3Ahttp%3A%2F%2Fvideo-cephrgw1.i%3A9091%2Fvideo4%2F75148598-v&p=f&expire_at=1662721200&touch=1662567073&reg=47&sign=fcdc3c53523ac97fa83557f260eb137a3d073599`;

    await this.capacitorVideoPlayer.initPlayer({
      mode: 'fullscreen',
      url: url,
      playerId: 'player1',
      title,
      smallTitle,
      accentColor: '#f0b400',
      chromecast: true
    })
```
directly without the headers it works well both in iOS and Android
so i think it is related to the headers where you seems to use cookies and i saw that 403 on exoPlayer can come from the use of cookies 
on top of this in the code you gave
```
      Http.get(options).then(data => {
        const json = data.data;
        let videos = [];
        json.videos.forEach(video => {
          videos.push({
            'label': video.key,
            'file': "https://" + video.url.substring(2),//delete the first two characters of url and add https://
            'referer': url
          });
        });

``` 
i think referer should be `referer`: options.url in the push but this does not change the error

**Comment by jepiqueau** [comment]
@PhantomPainX may be something related to 
`https://my.mail.ru/+/video/meta/9149163570439660295`

**Comment by jepiqueau** [comment]
@PhantomPainX if i look at the error in iOS
playerItem Error Optional(Error Domain=AVFoundationErrorDomain Code=-11829 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media may be damaged., NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x600001102820 {Error Domain=NSOSStatusErrorDomain Code=-12848 "(null)"}})

**Comment by jepiqueau** [comment]
@PhantomPainX I played all the morning with that i am pretty sure that the headers are not loaded from https://my.mail.ru/+/video/meta/9149163570439660295  i will stop on this letting you continue the research on iOS may be have a look at https://github.com/kevinjameshunt/AVPlayer-HTTP-Headers-Example

**Comment by PhantomPainX** [comment]
@jepiqueau I'm stupid... I was encoding the url damaging it in the process (changing key parts of the url, this caused the url gave me 403, because the server didn't recognize it lol)

I'm closing it because the error 1 was resolved and the error 2 wasn't even an error of your plugin ... (mediaplayer plugin played it successfully but this should be because it uses other way to call the request and encode urls)

Thanks for your time and sorry for my mistake...
