### ISSUE TITLE
Android crashes

### ISSUE THREAD

**Issue by phormula** [jepiqueau/capacitor-video-player#109]
```
java.lang.IllegalStateException: The fully qualified name of the implementation of OptionsProvider must be provided as a metadata in the AndroidManifest.xml with key com.google.android.gms.cast.framework.OPTIONS_PROVIDER_CLASS_NAME.
        at com.google.android.gms.cast.framework.CastContext.zzg(com.google.android.gms:play-services-cast-framework@@20.0.0:6)
        at com.google.android.gms.cast.framework.CastContext.getSharedInstance(com.google.android.gms:play-services-cast-framework@@20.0.0:4)
        at com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment.onCreateView(FullscreenExoPlayerFragment.java:186)
```

My app crashes on android, please help

**Comment by jepiqueau** [comment]
@phormula look at https://github.com/jepiqueau/angular-videoplayer-app-starter manifest file. You need to copy the <meta-data> block into your app manifest file.

**Comment by jepiqueau** [comment]
@PhantomPainX Can you modify the readme.md to include under Android the requirement to add the <meta-data> block for cast in the manifest file. Make a PR i will merge it

**Comment by jepiqueau** [comment]
@phormula look at the docs/API.md doc for Chromecast support it is all there. 
@PhantomPainX sorry it is all there. Nothing to do.

**Comment by phormula** [comment]
> @phormula look at the docs/API.md doc for Chromecast support it is all there. @PhantomPainX sorry it is all there. Nothing to do.

Thanks it worked

**Comment by jepiqueau** [comment]
@phormula OK i will close the issue

**Comment by jepiqueau** [comment]
@phormula thanks for using the plugin.
