### ISSUE TITLE
Player not working in xcode debug

### ISSUE THREAD

**Issue by KANekT** [jepiqueau/capacitor-video-player#110]
in debug in Xcode on virtual device player not work

file example 

"file:///Users/kanekt/Library/Developer/CoreSimulator/Devices/53EC4B83-9BF0-486E-8CC5-9837DFD9AAAE/data/Containers/Data/Application/4150AC88-2BF6-4A4B-A99F-612480EA56AD/Documents/82fef35dd40746cc96d2b3dd3987767d.mp4"

**Comment by jepiqueau** [comment]
@KANekT if you look at the API.md docs 
```
from Application Folder
iOS Plugin . application/files/video.mp4 is corresponding to : /data/Containers/Data/Applications/YOUR_APPLICATION/Documents/files/video.mp4
```
so your video file must be in
"file:///Users/kanekt/Library/Developer/CoreSimulator/Devices/53EC4B83-9BF0-486E-8CC5-9837DFD9AAAE/data/Containers/Data/Application/4150AC88-2BF6-4A4B-A99F-612480EA56AD/Documents/files/82fef35dd40746cc96d2b3dd3987767d.mp4"

**Comment by jepiqueau** [comment]
@KANekT so the url to give is
"application/files/82fef35dd40746cc96d2b3dd3987767d.mp4" This must work

**Comment by jepiqueau** [comment]
@KANekT or equivalent to above:
```
"file:///var/mobile/Containers/Data/Application/2D947973-BDBA-40A0-B20D-A995D35590C2/Documents/files/82fef35dd40746cc96d2b3dd3987767d.mp4"
```

now if you want to have it under the Documents folder
```
"file:///var/mobile/Containers/Data/Application/2D947973-BDBA-40A0-B20D-A995D35590C2/Documents/82fef35dd40746cc96d2b3dd3987767d.mp4"
```

**Comment by jepiqueau** [comment]
@KANekT Have you tried above. Please do answer

**Comment by jepiqueau** [comment]
@KANekT As i do not get any news from you i close the issue
