### ISSUE TITLE
Full Screen Android Issue

### ISSUE THREAD

**Issue by mattsputnikdigital** [jepiqueau/capacitor-video-player#116]
I am running my Android App in fullscreen and after a fullscreen video closes it breaks my layout as the plugin resets some layout properties.

Is there a way to tell when the video is stopped ( by adding code in MainActivity ) so I can readjust the layout and set the correct properties for the view.

**Comment by jepiqueau** [comment]
@mattsputnikdigital have you add listener in your typescript page . You can listen to `jeepCapVideoPlayerEnded` or to `jeepCapVideoPlayerExit`
