### ISSUE TITLE
Embedded subtitles for Android

### ISSUE THREAD

**Issue by Aymkdn** [jepiqueau/capacitor-video-player#125]
Hey

I have a mkv file with embedded subtitles in different languages. I'm not able to find a way to choose the language I want from the UI. I also tried to set `language:"fr"` when I call `initPlayer()`, but no subtitles are showing up at all.

Any idea how to deal with these video files?

Thanks

**Comment by Aymkdn** [comment]
I gave up, and I'm now using https://github.com/mpv-android/mpv-android

**Comment by jepiqueau** [comment]
@Aymkdn sorry i am away so i did not have time to look at it for mkv files
