### ISSUE TITLE
Picture-in-Picture

### ISSUE THREAD

**Issue by humeyra92** [jepiqueau/capacitor-video-player#126]
I am trying to use pip feature on ios and Android apps, is it possible to do this with this package?
Im receiving an error while doing so :

`Failed to execute 'requestPictureInPicture' on 'HTMLVideoElement': Must be handling a user gesture if there isn't already an element in Picture-in-Picture.`

**Comment by PhantomPainX** [comment]
Are you initializing the player in embedded mode? I think it only works in fullscreen mode. I'm not sure though.

**Comment by jepiqueau** [comment]
@humeyra92 It works also in embedded mode (Web only) but for one video only.

**Comment by jepiqueau** [comment]
@humeyra92 you said `I am trying to use pip feature on ios and Android apps` and you got `Failed to execute 'requestPictureInPicture' on 'HTMLVideoElement'` which is a web type of message. Can you elaborate more on what you do and on which platform you got this. I test it this morning on each platforms and it is working well. Can you share also your package.json file.

**Comment by jepiqueau** [comment]
@stephanevallejo Picture in Picture exists from release 3.3.x

**Comment by stephanevallejo** [comment]
Thanks for your reply @jepiqueau 
I've just tested my application on my iPhone and the Picture and Picture function works. 
The icon doesn't appear with the iOS Simulator.

**Comment by jepiqueau** [comment]
@stephanevallejo  look at [Ionic7Angular-VideoPlayer-App](https://jepiqueau.github.io/2023/11/08/Ionic7Angular-VideoPlayer-App.htm). It is true that you cannot see it on the iOS simulator, you must test it on an iPAD simulator. I never find the reason for this.

**Comment by stephanevallejo** [comment]
Hello,

I confirm, it works.

- On Android, add
`android:supportsPictureInPicture="true"`
in activity of AndroidManifest.xml

- On iOS, test application on physical device
