### ISSUE TITLE
Feature request: background video support

### ISSUE THREAD

**Issue by 7freaks-otte** [jepiqueau/capacitor-video-player#13]
Any plans on supporting background videos?

Seems to be quite easy for iOS: https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/creating_a_basic_video_player_ios_and_tvos/playing_audio_from_a_video_asset_in_the_background

In my special case we are streaming music videos which is (at least on iOS) working perfectly and it would be nice to keep the audio (or video via Airplay) running when I switch to another app.

**Comment by jepiqueau** [comment]
@7freaks-otte It is not as easy in fact, as it is not the player which is on the background but the application itself which go the capacitor-bridge to get the player. So i will see how it comes when i will try. Thanks anyhow to bring this

**Comment by 7freaks-otte** [comment]
It was in fact very easy to allow background streaming on iOS by adding just a few lines to your plugin, BUT:

At the moment my App stops playing the video when it enters background but playback can be reactivated on the lockscreen or in the control center. Then it continues playing in the background and streaming over airplay.

I’m still trying to solve this and keep you posted about my progress..

**Comment by jepiqueau** [comment]
@7freaks-otte Can you share the changes you made to the plugin so i can test on my side

**Comment by 7freaks-otte** [comment]
Of course I will. I just thought I could give you a more sophisticated solution that I fully understand and that is ready to be incorporated into your plugin... 🙈
I’ll post my (trial & error) changes tomorrow as soon as I’m in my office

**Comment by jepiqueau** [comment]
@7freaks-otte Ok thanks, On my side i made a pure swift video player app where the sound continue to play when the app is in a background but i have not succeed yet to implementing it the plugin and in the app using the plugin i do not know how to pass the viewController define in the plugin to the app running the plugin

**Comment by 7freaks-otte** [comment]
I was merely setting the AudioSession to “shared” with a background-Audio category. On didEnterBackground detaching the player and on willEnterForeground reattaching it. I post my code tomorrow.

**Comment by jepiqueau** [comment]
@7freaks-otte this is what i am looking to do but i cannot find the way to transfer the audioSession and the player from the plugin to the AppDelegate of the application

**Comment by 7freaks-otte** [comment]
To be honest, I'm not really sure what I am doing here, as I did not have the time to dig more into it and I just coded it for videoPlayerFullScreenView as this is what we are using.

But I share my code with you along with my assumptions why it works.

First I added a variable to keep a reference to the player when detaching:
```var playerBg: AVPlayer!```

Then I added the code for the shared Audio category right before your `if (mode == "fullscreen")`. (I read somewhere that this should be done as soon as possible. At least before the video/audio starts.)
```
@objc func initPlayer(_ call: CAPPluginCall)  {
	...

	let audioSession = AVAudioSession.sharedInstance()
	do {
		// Set the audio session category, mode, and options.
		try audioSession.setCategory(.playback, mode: .moviePlayback, options: [])
		let _ = try AVAudioSession.sharedInstance().setActive(true)
	} catch {
		print("Failed to set audio session category.")
	}

	...
}
```
I haven't tried any other category yet, if this solves pausing the player when the app enters background. My colleagues think that the reason could also be our stream encoding that prevents a seamless switch and forces me to press play again (on the lock screen) when the app is in background.

Then I added two functions to your Plugin.swift to disconnect/reconnect the player:
```
func applicationDidEnterBackground(_ application: UIApplication) {
	// Disconnect the AVPlayer from the presentation when entering background
	if (self.videoPlayerFullScreenView != nil) {
		self.playerBg = self.videoPlayerFullScreenView.player
		self.videoPlayerFullScreenView.player = nil
	} else {
		self.playerBg = nil
	}
}

func applicationWillEnterForeground(_ application: UIApplication) {
	// Reconnect the AVPlayer to the presentation when returning to foreground
	if (self.playerBg != nil) {
		self.videoPlayerFullScreenView.player = self.playerBg
	}
}
```

This seems to be enough to pass the player to the OS in background and reattach it on entering foreground.

As I mentioned before, I suspect 3 possible reasons why my player pauses when entering background, but I had no time yet to check my assumptions:
1) iOS might force a Video to pause because it assumes that the visual part is important and the user wants to continue playing later (this is what happens in the Netflix app). Maybe this can be solved to by changing the audio category and mode (moviePlayback) to something else like "ambient"
2) Maybe I just need to start playback again after detaching in applicationDidEnterBackground
3) It might also be our video stream because before setting the audio session to shared, iOS faded the audio out smoothly which tells me that it was intentionally. Now it stops suddenly which supports my colleagues' opinion that it might be the decoding of our stream that is breaking and needs to be restarted.

However background audio (even with streaming over AirPlay) works with the above changes to your plugin. All I changed to my app was enabling background audio in Xcode.

**Comment by jepiqueau** [comment]
@7freaks-otte Thanks for sharing, i saw that you create two new methods in the plugin applicationDidEnterBackground and applicationWillEnterForeground where i was trying to do the same code in the AppDelegate.swift of the application but i din't find the way to pass the player and the audioSession from the plugin to the application.This is strange, i thought that it is the application which goes foreground not the plugin. I am going to replicate what you did and see how it works. for the moment only the fullscreen part of the plugin is validated the tableViewController is under development.

**Comment by 7freaks-otte** [comment]
You are completely right. I haven’t tested really tested if applicationDidEnterBackground gets called but I received an error before I added the nil-Test in applicationWillEnterForeground so I assumed that it was in fact called

**Comment by jepiqueau** [comment]
@7freaks-otte I have tested your code but both the audio and the video stop when the app is entering the background. i check that the app target capabilities i have Background Modes set for Audio, Airplay, and Picture in Picture

**Comment by 7freaks-otte** [comment]
After it stops, can you start the audio again on your Phone’s lock screen? This is what I am able to do and which tells me, that background mode is working correctly.

I will test if my 2 new functions are called in the XCode console

**Comment by jepiqueau** [comment]
@7freaks-otte No i didn't test other mode for the audio session but i could try to see the difference. I do not have an Apple device so i can only test on simulator can you explain me What is the Phone's lock screen sorry for this

**Comment by 7freaks-otte** [comment]
Start your video in the simulator:

![Simulator Screen Shot - iPhone 11 - 2020-05-11 at 12 54 32](https://user-images.githubusercontent.com/11407404/81554297-d237e280-9386-11ea-8dbd-73ab67711a12.png)

Then in the Simulator-Menu go to the Home-Screen (> Hardware > Home / Cmd-Shift-H).
Wait until your video stops.

Now in the Simulator-Menu lock the Phone (> Hardware > Lock / Cmd-L)
The phone is black now.

Now select press Home again (> Hardware > Home / Cmd-Shift-H).
You will see the screen again to unlock the phone but it should also show that music was playing.

![Simulator Screen Shot - iPhone 11 - 2020-05-11 at 12 55 41](https://user-images.githubusercontent.com/11407404/81554642-73bf3400-9387-11ea-95f8-3c660d7c55fb.png)

Here I can press "Play" again and the audio of my app continues to play in background.

Now I can do anything on my phone or lock it again and my video (at least the audio) continues to play in background all the time.

This tells me that my code works in principal, that background audio is working and I just have to find out why it first stops playing when entering background mode although I can start it again through this lock screen

**Comment by jepiqueau** [comment]
@7freaks-otte i did follow what you said and it works but the first time you have to press on play. This is the behavior that you have too ?

**Comment by 7freaks-otte** [comment]
Yes, that is the same behaviour.

This means:
1) The problem is not our stream... 🙈
2) Background audio is working
3) We have to find out why iOS initially stops playing the video

Maybe we can change that behaviour with a different audio session mode. Or maybe there is a problem with detaching the player in my applicationDidEnterBackground function

**Comment by jepiqueau** [comment]
@7freaks-otte Well in fact i put a print inside the 2 functions and it did not show them in the Xcode console meaning that it does not go through the two functions but i got on the console APP INACTIVE or APP ACTIVE so it is going somewhere else i will try to figure out

**Comment by 7freaks-otte** [comment]
OK then this might be the problem. I just found out that there must be a possibility to "subscribe" to applicationDidEnterBackground from within your plugin outside of the app delegate.

https://www.hackingwithswift.com/example-code/system/how-to-detect-when-your-app-moves-to-the-background (ObjC though)

Unfortunately Swift is not my daily work either ;-)

**Comment by 7freaks-otte** [comment]
Can you test something like this?

```
NotificationCenter.default.addObserver(forName: UIApplication.didEnterBackgroundNotification, object: nil, queue: nil) {
    ...
}
```

(Found here: https://stackoverflow.com/a/51589649)

**Comment by jepiqueau** [comment]
@7freaks-otte i go it working but as i thought at the beginning it has to be done in the AppDelegate and  the way to pass the ViewController from the plugin to the AppDelegate which was my problem yesterday i solve it by adding a listener. I am going to give you the code as i tested only for the fullscreen so before to release it i have to check that it works also for the TableViewController.

**AppDelegate.swift**
```swift
    var window: UIWindow?
    var videoPlayer: AVPlayerViewController?
    var bgPlayer : AVPlayer?

  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    // Add an Observer to get the playerViewController     
    NotificationCenter.default.addObserver(self, selector: #selector(playerViewControllerReceived(notification:)), name: Notification.Name("playerViewController"), object: nil)
    return true
  }
...
func applicationDidEnterBackground(_ application: UIApplication) {
    print("in applicationDidEnterBackground ")
    bgPlayer = videoPlayer!.player
    videoPlayer!.player = nil
  }
  func applicationWillEnterForeground(_ application: UIApplication) {
    print("in applicationWillEnterForeground ")
    videoPlayer!.player = bgPlayer
  }
...
  @objc func playerViewControllerReceived(notification: Notification) {
    self.videoPlayer = (notification.object as! AVPlayerViewController)
  }
```

**Plugin.swift**
```swift
public class CapacitorVideoPlayer: CAPPlugin {
     
    public var player: AVPlayer!
    public var call: CAPPluginCall!
    public var videoPlayer: AVPlayerViewController!
    var videoPlayerTableViewController: VideoPlayerTableViewController!
    var videoPlayerFullScreenView: FullScreenVideoPlayerView!
    var audioSession: AVAudioSession!
    var mode : String!
    var playerList: [String: SmallVideoPlayerView] = [:]
...

    @objc func initPlayer(_ call: CAPPluginCall)  {
...
       if (mode == "fullscreen") {
            guard let url = call.options["url"] as? String else {
                let error:String = "VideoPlayer initPlayer: Must provide a video url"
                print(error)
                call.reject(error)
                return
            }
            
            self.audioSession = AVAudioSession.sharedInstance()
            do {
                // Set the audio session category, mode, and options.
                try self.audioSession.setCategory(.playback, mode: .moviePlayback, options: [])
             } catch {
                print("Failed to set audio session category.")
             }

            DispatchQueue.main.async {
                self.videoPlayerFullScreenView = FullScreenVideoPlayerView(videoPath: url)
                // post notification to pass videoPlayerFullScreenView.videoPlayer to AppDelegate
                NotificationCenter.default.post(name: .playerViewController, object: 
                self.videoPlayerFullScreenView.videoPlayer)
                // Present the Player View Controller 
                self.bridge.viewController  .present(self.videoPlayerFullScreenView.videoPlayer, animated: 
                   true, completion:{
                    do {
                        // Activate the audio session.
                        self.audioSession = self.videoPlayerFullScreenView.audioSession
                        try
                            self.audioSession.setActive(true)
                        self.videoPlayerFullScreenView.player.play()
                    } catch {
                        let error:String = "VideoPlayer initPlayer: Failed to set audio session category"
                        print(error)
                        call.reject(error)
                        return
                    }
                });
            }
        } else if (mode == "embedded") {
...
```

and add in **Notification.Name.swift**

```swift
    static var playerViewController: Notification.Name{return .init(rawValue: "playerViewController")}
``` 
This should give you now what you were looking for. tell me if not

**Comment by 7freaks-otte** [comment]
Sounds good, I will test that tomorrow. I just thought we could work around the AppDelegate by using a listener in your plugin:

```
NotificationCenter.default.addObserver(forName: UIApplication.didEnterBackgroundNotification, object: nil, queue: nil) { (notification) in
    print("in applicationDidEnterBackground ")
    bgPlayer = videoPlayer!.player
    videoPlayer!.player = nil
}
```

**Comment by jepiqueau** [comment]
@7freaks-otte Yes it could do to i will look at it as i do not like to have to modify the AppDelegate which make thinks more complicate for the user Let see

**Comment by 7freaks-otte** [comment]
@jepiqueau That was my thought too. Hopefully it works out :-)

**Comment by jepiqueau** [comment]
@7freaks-otte  il will know that soon

**Comment by jepiqueau** [comment]
@7freaks-otte Unfortunately it doesn't  as the bridge get the signal before the plugin so it stop the video playing in the background. I do not know if it can be considered as a bug

**Comment by jepiqueau** [comment]
@7freaks-otte Finally it works after some trials and errors
The **AppDelegate.swift** should not be modified at all

the **Plugin.swift** file should be modified as followed

```swift
public class CapacitorVideoPlayer: CAPPlugin {
     
    public var player: AVPlayer!
    public var call: CAPPluginCall!
    public var videoPlayer: AVPlayerViewController!
    public var bgPlayer: AVPlayer!
    var videoPlayerTableViewController: VideoPlayerTableViewController!
    var videoPlayerFullScreenView: FullScreenVideoPlayerView!
    var audioSession: AVAudioSession!
    var mode : String!
    var playerList: [String: SmallVideoPlayerView] = [:]
...
    override public func load() {
...
        NotificationCenter.default.addObserver(forName: UIApplication.didEnterBackgroundNotification, 
            object: nil, queue: nil) { (notification) in
            print("in pluginDidEnterBackground ")
            self.bgPlayer = self.videoPlayerFullScreenView.videoPlayer.player
            self.videoPlayerFullScreenView.videoPlayer.player = nil
        }
        NotificationCenter.default.addObserver(forName: UIApplication.willEnterForegroundNotification, 
           object: nil, queue: OperationQueue.main) { (notification) in
            print("in pluginWillEnterForeground ")
            self.videoPlayerFullScreenView.videoPlayer.player = self.bgPlayer
        }
    }
    @objc func initPlayer(_ call: CAPPluginCall)  {
        self.call = call

        guard let mode = call.options["mode"] as? String else {
            let error:String = "VideoPlayer initPlayer: Must provide a Mode (fullscreen/embedded/intable)"
            print(error)
            call.reject(error)
            return
        }
        self.mode = mode
        if (mode == "fullscreen") {
            guard let url = call.options["url"] as? String else {
                let error:String = "VideoPlayer initPlayer: Must provide a video url"
                print(error)
                call.reject(error)
                return
            }
            
            self.audioSession = AVAudioSession.sharedInstance()
            do {
                // Set the audio session category, mode, and options.
                try self.audioSession.setCategory(.playback, mode: .moviePlayback, options: [])
            } catch {
                print("Failed to set audio session category.")
            }

            DispatchQueue.main.async {
                self.videoPlayerFullScreenView = FullScreenVideoPlayerView(videoPath: url)

                // Present the Player View Controller 
                self.bridge.viewController  .present(self.videoPlayerFullScreenView.videoPlayer, animated: 
                    true, completion:{
                    do {
                        // Activate the audio session.
                        self.audioSession = self.videoPlayerFullScreenView.audioSession
                        try
                            self.audioSession.setActive(true)
                        self.videoPlayerFullScreenView.player.play()
                    } catch {
                        let error:String = "VideoPlayer initPlayer: Failed to set audio session category"
                        print(error)
                        call.reject(error)
                        return
                    }
                });
            }
        } else if (mode == "embedded") {

```
That is it

**Comment by jepiqueau** [comment]
@7freaks-otte new release published capacitor-video-player@2.1.0-1 which fix the issue. Thanks for having ask for and help me to solve it. great job together

**Comment by 7freaks-otte** [comment]
@jepiqueau I just tested it, everything is working perfectly. Thanks for addressing this issue, glad I could drop some hints and help a little bit. I really enjoyed working with you on this.

**Comment by jepiqueau** [comment]
@7freaks-otte You are welcome, i started to look at how to implement this for Android, it is a bit more complex, I hope i will succeed too. Thanks again

**Comment by 7freaks-otte** [comment]
@jepiqueau I'm afraid I cannot help you with Android... 🙈 But I made some improvements today to the iOS implementation to restore the ControlCenter-/LockScreen-Control that somehow disappeared when we implemented the background mode.

I'll share them with you later here.

BTW I sent you an email to the email address mentioned in your github profile.

**Comment by jepiqueau** [comment]
@7freaks-otte Ok, i do not know ControlCenter-/LockScreen-Control  as i do not have a physical Apple device. Can you also check that if a call is upcoming the sound play on a background is stopped as i think it should be the normal behavior isn't it?

**Comment by 7freaks-otte** [comment]
@jepiqueau Good point, I will check that. I'm sure the sound will be stopped as this is something iOS handles but I think the sound will not automatically resume. I some some code online that handles auto resume. Maybe I can implement that too.

**Comment by jepiqueau** [comment]
@7freaks-otte On IOS device how do you stop playing in background ?

**Comment by jepiqueau** [comment]
@7freaks-otte  I come back to you, are you still using the plugin if yes can you try the latest release and tell me if the background video audio is still working ? In the simulator it does not but i do not know the reason why? Your help will be appreciate

**Comment by 7freaks-otte** [comment]
@jepiqueau Our project has currently stalled but I'll see what I can do the next days. Will update dependencies and try to test your plug-in.

**Comment by jepiqueau** [comment]
@7freaks-otte thank you
