### ISSUE TITLE
Back button is locking to portrait orientation

### ISSUE THREAD

**Issue by daleyjem** [jepiqueau/capacitor-video-player#136]
Using this plugin for an app that runs on a TV (Amazon Fire or Google TV), but I also see the behavior on my phone... 
After I back out of the video, it appears to switch and lock to portrait orientation (which totally messes up the appearance on a TV).

These are my init options:

```typescript
    const result = await this.player.initPlayer({
        url: this.props.src,
        mode: 'fullscreen',
        playerId: VIDEO_PLAYER_ID,
        bkmodeEnabled: false,
        chromecast: false,
        displayMode: 'landscape',
        pipEnabled: false,
        showControls: false,
        width: 1920,
        height: 1080,
    })
```

**Comment by jepiqueau** [comment]
@daleyjem  Can you comment these lines (571 to 575) in FullscreenExoPlayerFragment.java and tell me if it works like you wish.
```
    Activity mAct = getActivity();
    int mOrient = mAct.getRequestedOrientation();
    if (mOrient == ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE) {
      mAct.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
    }

```

**Comment by jepiqueau** [comment]
@daleyjem You will have also to comment lines 353 to 357 when the video ended.

**Comment by jepiqueau** [comment]
@daleyjem Did you try?

**Comment by daleyjem** [comment]
@jepiqueau Sorry. I just got back from vacation. I actually ended up using `displayMode` = `'all'`, and I think it was fixed. I didn't see it as an option in the docs. I still have more testing to do in my app, so I'm gonna keep this one in my back pocket if other issues pop up, but thanks so much for the reply.

**Comment by jepiqueau** [comment]
@daleyjem yes i have to review this again but it is true that if you defined displayMode as something different than portrait or landscape it will work. So i will review the code for the next release

**Comment by jepiqueau** [comment]
@daleyjem thanks for the feedback

**Comment by Jmvega-code** [comment]
I encountered a similar issue where the landscape mode wasn't functioning correctly on Android devices. To resolve it, I modified the displayMode setting to "all". Moreover, to ensure that the change was effective, I had to add android:screenOrientation="fullSensor" within the <activity> tag in the androidManifest.xml file. Without this additional modification, the landscape mode did not work as intended.

**Comment by Jmvega-code** [comment]
I encountered a similar issue where the landscape mode wasn't functioning correctly on Android devices. To resolve it, I modified the displayMode setting to `"all"`. Moreover, to ensure that the change was effective, I had to add `android:screenOrientation="fullSensor"` within the `<activity>` tag in the androidManifest.xml file. Without this additional modification, the landscape mode did not work as intended.

**Comment by Jmvega-code** [comment]
@jepiqueau Hi Jean Pierre, yeah I'm using version 5.0.1

**Comment by jepiqueau** [comment]
@Jmvega-code please use the latest one 5.0.4-1

**Comment by Jmvega-code** [comment]
I just updated the version to the latest one. I used the same solution I provided above to solve the issue.

**Comment by jepiqueau** [comment]
@Jmvega-code i would like to know if it works without using the solution you provided above.
