### ISSUE TITLE
Android Custom Controls

### ISSUE THREAD

**Issue by sClarkeDevz** [jepiqueau/capacitor-video-player#137]
is it possible to use overlay controls on android? i have disabled default controls using "showControls" and am trying to render a div ontop of the player but it is always under the player.

`const Player: React.FC<Props> = () => {
  return (
    <IonPage>
      <div id="fullscreen" />
      <div className="absolute top-0 left-0 right-0 bottom-0 z-50">
        <p>OVERLAY</p>
      </div>
    </IonPage>
  );
};
`

`
Player init config:
        playerId: 'fullscreen',
        url: TEST_VIDEO,
        mode: 'fullscreen',
        bkmodeEnabled: false,
        chromecast: false,
        displayMode: 'landscape',
        pipEnabled: false,
        showControls: false,
        componentTag: 'div'`

**Comment by jepiqueau** [comment]
@sClarkeDevz This is not possible the android part of the plugin use Exoplayer and is written in Java, so nothing to do with a HTML div element which is part of the web view.
