### ISSUE TITLE
Add support for url without type

### ISSUE THREAD

**Issue by gabsgasps** [jepiqueau/capacitor-video-player#14]
Hey ! add support for url without type, without create manually a raw folder under the res folder.

**Comment by jepiqueau** [comment]
@gabsgasps Can you be more precise, i do not understand what you mean by "url without type". Do you mean a video from your device disk ?

**Comment by gabsgasps** [comment]
@jepiqueau like this 
https://universo-dev-a-m.s3.amazonaws.com/779970/fe774806dbe7ad042c24ce522b7b46594f16c66e

**Comment by jepiqueau** [comment]
@gabsgasps Ok understand, but in that case Do you know a way to identify the type

**Comment by jepiqueau** [comment]
@gabsgasps I tried your link in the web and i can use the normal video tag with the type "video/mp4" so i will use this in the next release as i have to check how it is behaving in ios and android

**Comment by gabsgasps** [comment]
> @gabsgasps Ok understand, but in that case Do you know a way to identify the type

i found this https://stackoverflow.com/questions/24050112/check-url-content-type-with-javascript/24050265#24050265
_but it works only if they have CORS_

**Comment by jepiqueau** [comment]
@gabsgasps this is now fixed in capacitor-video-player@2.1.0-2
