### ISSUE TITLE
Automatic rotation on Android

### ISSUE THREAD

**Issue by stephanevallejo** [jepiqueau/capacitor-video-player#141]
Hello,

I use Ionic 7, Capacitor 5 and capacitor-video-player@5.0.2

Here is my code

`openVideo() {
    CapacitorVideoPlayer.initPlayer({
      mode: "fullscreen",
      pipEnabled: true,
      bkmodeEnabled: true,
      playerId: "live",
      url: "https://XXXXXX/playlist.m3u8"
    });
  } `

Without the "displayMode" parameter, on iOS the video turns when I turn the phone. 
Without the "displayMode" parameter, on Android the video does not rotate when I turn the phone.
I added the "displayMode" parameter to "all" but on Android the video doesn't turn when I turn the phone. 
If I set the "displayMode" parameter to "landscape", on Android the video automatically rotates in landscape, but there's no portrait-landscape toggling possible.

**Comment by jepiqueau** [comment]
@stephanevallejo update to release 5.5.0 and tell me if it is fixed

**Comment by stephanevallejo** [comment]
Hello @jepiqueau 

`npm install --save capacitor-video-player@5.5.0`
`ionic cap sync`
`ionic cap open android`

I tested without displayMode and with displayMode: "all"
It doesn't work
<img width="541" alt="Capture d’écran 2023-12-08 à 19 44 01" src="https://github.com/jepiqueau/capacitor-video-player/assets/54773808/b5c31117-46eb-4bab-b71b-fb2e485952e2">

**Comment by stephanevallejo** [comment]
I tested it on a physical device but it didn't work either.
Another bug: when I click on the Fullscreen icon in the top right-hand corner, the image becomes distorted.
<img width="541" alt="Capture d’écran 2023-12-08 à 20 04 42" src="https://github.com/jepiqueau/capacitor-video-player/assets/54773808/576f08de-4f65-4bde-9216-9a8210a7d448">

**Comment by PhantomPainX** [comment]
> Another bug: when I click on the Fullscreen icon in the top right-hand corner, the image becomes distorted.
> 

It's not a bug, it's supposed to be that way. It has three modes: normal, tight on screen and zoom

**Comment by stephanevallejo** [comment]
Ok, thank for your reply for Fullscreen. 
For automatic rotation, any solution ?

**Comment by PhantomPainX** [comment]
I'm not able to test the last version of the plugin, but the one I use (5+), the rotation works perfectly.

Do you have any plugin or setting that blocks rotation in your app?

**Comment by jepiqueau** [comment]
@stephanevallejo When you do not set displayMode it takes the default which is "all". I test it again this morning and it works well. have you got this in your AndroidManifest.xml
```xml
<activity
...            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
...
</activity>
```

**Comment by stephanevallejo** [comment]
@jepiqueau I have the line of code you mention
@PhantomPainX was right, the problem came from :
`android:screenOrientation="portrait"`
which I had added to activity in AndroidManifest.xml
Unlike iOS, it's not possible to lock the app in portrait mode and play videos in any direction.
On Android, you need to globally authorize the application to rotate by not having the line of code with the "android:screenOrientation" parameter, or by configuring it to authorize certain rotations.
