### ISSUE TITLE
Player not working on web platform (embedded and fullscreen)

### ISSUE THREAD

**Issue by choozn** [jepiqueau/capacitor-video-player#144]
The player is not initialized despite returning a success object and preloading the content.
I've tried the library in both svelte and astro. Same behavior for both.

## Expected Behavior
The player should be initialized as specified in the docs.

## Current Behavior
A success object is returned, but the player is not initialized.
Using the `fullscreen` mode, the sound of the video is played but no player is visible. A fullscreen request is denied.
Using the `embedded` mode, nothing happens besides preloading the content and returning the success object.

```
{
  "method": "initPlayer",
  "result": true,
  "value": true
}
```

## Steps to Reproduce
```html
<script>
import { CapacitorVideoPlayer, type capVideoPlayerOptions } from "capacitor-video-player";

document.getElementById("play")?.addEventListener("click", async () => {
  const playerOptions: capVideoPlayerOptions = {
    url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    mode: "embedded",
    playerId: "player",
    componentTag: "div",
  };

  const player = await CapacitorVideoPlayer.initPlayer(playerOptions);
  console.log(player);
})
</script>

<div id="player"></div>
<button id="play">Test</button>
```

## Context (Environment)
- AstroJS / Svelte

**Comment by jepiqueau** [comment]
@choozn can you share your complète code on github

**Comment by choozn** [comment]
Sure. I'll provide it throughout the day.

**Comment by choozn** [comment]
I've published a project on github to reproduce the bug: https://github.com/choozn/bug-showcase-capacitor-video-player
