### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lewdea** [jepiqueau/capacitor-video-player#15]
Currently, the native player does not support interactive apis as many as web plugin does. Do you have any plans or roadmap that can share with us? Thanks.

**Comment by jepiqueau** [comment]
@lewdea , Thanks for your question, my first thought was that the API are required when you embed the player, that the reason why i do not expose them in native as there is only a fullscreen mode yet. Do you need the API in fullscreen mode ? If yes tell me and i will have a look

**Comment by lewdea** [comment]
@jepiqueau  Thanks for the reply.  I've already embed the player into my capacitor project and it can play the video in fullscreen mode. However, for me, video play is only the first step. What I want the most is the video tracking when the app is installed and used in native devices.  My request is whether you can expose more apis as many as web plugin does, such as getDuration, fire play/pause event with detail and etc..  I'm not a native English speaker and I hope I've made myself clear to you.

**Comment by jepiqueau** [comment]
@lewdea I understand clearly your point, i am working on, it is taking more time that what i thought as i have also to implement listeners and notification to make sure that you could use the API when the player is ready to play. I hope i will have it soon first for the IOS plugin and later for the Android. Thanks for using the plugin

**Comment by jepiqueau** [comment]
@lewda The new release 2.1.0 give access to the interactive apis for the native players. It took sometimes as i had to completely rewrite the two natives players. Hope you will enjoy...
