### ISSUE TITLE
default playerId `fullscreen` work but another one doesn't

### ISSUE THREAD

**Issue by mirsella** [jepiqueau/capacitor-video-player#150]
hello !

```html
    <div id="fullscreena"></div>
```
And
```ts
  await CapacitorVideoPlayer.initPlayer({
    url: url.href,
    playerId: "fullscreena",
    componentTag: "div",
    mode: "fullscreen",
    title,
    chromecast: false,
  });
    await CapacitorVideoPlayer.setVolume({
      playerId: "fullscreena",
      volume: 0.4,
    }),
```
The initplayer works, the video initialize well and works, but i get a `Given PlayerId does not exist` from setvolume. just replacing the 3 references from `fullscreena` to `fullscreen` and it works.

Sorry if there is missing information, i would gladly give more if needed !

thanks !

**Comment by paulisidore** [comment]
Hi @mirsella , the id "fullscreen" is mandatory and mentioned in the documentation. It's better not to change it.

**Comment by mirsella** [comment]
ohh it explains it, I thought it could be changed as its given manually to functions

thanks !
