### ISSUE TITLE
Play videos from local storage

### ISSUE THREAD

**Issue by itsmebharat** [jepiqueau/capacitor-video-player#19]
Please add feature to play videos from device local storage, currently it's supported. Thanks!

**Comment by jepiqueau** [comment]
@itsmebharat this feature has been added  in the new beta release **capacitor-video-player 2.3.0-beta.4** can you tell me if that is working for you ?  (only for iOS and Android platforms)

**Comment by itsmebharat** [comment]
@jepiqueau Great thanks, I will check and confirm.

**Comment by jepiqueau** [comment]
@itsmebharat Did you had time to check?

**Comment by itsmebharat** [comment]
Hello @jepiqueau sorry for late reply. 
I saw your latest plugin code and I think it is not matching with my requirement which you have implemented. 

In my app I want to play video by following these steps:
1. Play video from http url  (Working with plugin code)
2. If user download video using download button, save it to internal storage in app sandbox. eg: **file:///data/user/0/com.jeep.capacitor.app/files/video1.mp4** (Working with my code)
3. Play video using internal storage path eg: **file:///data/user/0/com.jeep.capacitor.app/files/video1.mp4**

For example:
` this._url = File.dataDirectory+"video1.mp4"`
`const res:any  = await this._videoPlayer.initPlayer({mode:"fullscreen",url:this._url,playerId:"fullscreen",componentTag:"app-home"});`

So as you see, this kind of url is still not handled in your code so it is still not working. 

However it works as i said if i pass url as: **/data/user/0/com.jeep.capacitor.app/files/video1.mp4** and if I change your code 

from
`videoPath = "android.resource://" + context.getPackageName() + "/" + url;` 
to
`videoPath = url;`


I saw you have implemented 

` if (url.equals("internal")) {
                    createPickerVideoFragment(call);
                } `

but i don't know what do you mean by "**internal**" here? 

Again thank you for your efforts.

**Comment by itsmebharat** [comment]
@jepiqueau Yes I was assuming same and I did try in the same sample repo you sent me, and I changed url as "internal" but it is not working. I only see white screen when I hit video play button.

![image](https://user-images.githubusercontent.com/5227949/91161920-08586280-e6e9-11ea-9195-889b2bd439bb.png)

**Comment by jepiqueau** [comment]
@itsmebharat Did you try downloading `https://github.com/jepiqueau/angular-videoplayer-app-starter` i updated it  so it should work tell me if not

**Comment by jepiqueau** [comment]
@itsmebharat Did you synchronize your project on Android ?

**Comment by itsmebharat** [comment]
@jepiqueau yes I did. 

`npx cap sync`

I was using stencil repo not angular.

**Comment by jepiqueau** [comment]
@itsmebharat No i am talking in Android Studio `sync project with gradle files` and do you have `    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>` in your manifest file Do you have any videos in your 
`data/media/0/ Movies/ folder? Now thinking about it if there is no video you got a white screen and you cannot get out which is a bug so may be this is your case?

**Comment by itsmebharat** [comment]
@jepiqueau And when i put video in the external storage it is working.

![image](https://user-images.githubusercontent.com/5227949/91191145-08208d00-e712-11ea-884b-bff0a7dccc6c.png)

**Comment by itsmebharat** [comment]
@jepiqueau one suggestion, on the video selection page if I click back button, I should go back to the previous screen, there is no way to go back without playing video and hit back. I hope that make sense. Thanks

**Comment by jepiqueau** [comment]
@itsmebharat Yes you right but as it is a fragment the onBackPressed doesn't work so i am doing it right now with a notification sending back 0 files found it will be in the next release thanks for helping me debugging and sorry for any inconvenience on your side. i have also to check on iOS if there is no video. Otherwise when it works is it ok for you meaning that the videos will stand in 
`file:///data/media/0/ Movies/video1.mp4`  
and not  in 
`file:///data/user/0/com.jeep.capacitor.app/files/video1.mp4`

**Comment by itsmebharat** [comment]
@jepiqueau thank you and no problem to help you in future as well for debugging this plugin. 

Sorry but your solution won't work for me as I can't keep downloaded videos in the external storage and visible to user. My app requirement is video should be stored in the app data only and they should be played from that path only and when app gets uninstall all videos should be removed.

**Comment by jepiqueau** [comment]
@itsmebharat ok i understand. Can you then clarify
`If user download video using download button, save it to internal storage in app sandbox. eg: file:///data/user/0/com.jeep.capacitor.app/files/video1.mp4 (Working with my code)`
i assume the download button and the storage in  `file:///data/user/0/com.jeep.capacitor.app/files/video1.mp4` is done in your application so i just have to use the url which is given, i will have a look if i can add this too.

**Comment by itsmebharat** [comment]
@jepiqueau Yes you right, and to workaround this as I mentioned above I had to do two things.

First I had to remove `file://` from my url `file:///data/user/0/com.jeep.capacitor.app/files/video1.mp4` so it become `/data/user/0/com.jeep.capacitor.app/files/video1.mp4`
and changed your code from

`videoPath = "android.resource://" + context.getPackageName() + "/" + url;`
to
`videoPath = url;`

Let me know the better way to do if you've got some time. Thank you.

**Comment by jepiqueau** [comment]
@itsmebharat added to the new release 2.3.0 of the plugin.
you have to define the url as 
`application/files/movie.mp4` 

## Application Folder

- iOS Plugin
  . "application/files/video.mp4" is :
  `/data/Containers/Data/Applications/YOUR_APPLICATION/Documents/files`

- Android Plugin
  . "application/files/video.mp4" is :
  `/data/user/0/YOUR_APPLICATION_PACKAGE/files/`

i assume that this folders are created and the video are downloaded before calling the plugin 
Voilà Cordialement

**Comment by itsmebharat** [comment]
@jepiqueau Thank you, I will test and close it.

**Comment by jepiqueau** [comment]
@itsmebharat as i didn't hear anything, i assume you test it and it is working so i close the issue

**Comment by Shanmt** [comment]
@jepiqueau , I tried the same in my Android.  Passed  the URL as `/data/user/0/APPLICATION_PACKAGE/files/1.mp4`. But video is not playing. I tried with files `file:///data/user/0/APPLICATION_PACKAGE/files/1.mp4` also. Both not working. Am I missing something. Thanks You.

**Comment by jepiqueau** [comment]
@Shanmt thanks for using the plugin. Ss mentioned above the url should be `application/files/movie.mp4` or in your case `application/files/1.mp4`

**Comment by Shanmt** [comment]
@jepiqueau Thank you. It works. :)
