### ISSUE TITLE
Exit video player!

### ISSUE THREAD

**Issue by Sina7312** [jepiqueau/capacitor-video-player#2]
What if someone tried to exit the video player?! Is there an ability for it?

**Comment by jepiqueau** [comment]
sorry to respond late, on which platform, the web ? on ios it is implemented, on android the press back button exit the video,

**Comment by Sina7312** [comment]
Thanks for responding. Yes, I test it on web and there was no way to exit in middle of video.

**Comment by jepiqueau** [comment]
i am looking for it, but it is not as easy

**Comment by jepiqueau** [comment]
i did add a button in the web interface to close in the release 1.0.0-alpha.6, i have still to manage the hiding and showing i did not find an event from the video tag controls which is fired when the controls are shown or hide so i will have to do something not synchronized

**Comment by Sina7312** [comment]
Thanks for the update

**Comment by jepiqueau** [comment]
This is now solved in in the release 1.0.0-beta.1, so i close it
