### ISSUE TITLE
Destroy all listeners attached to a player

### ISSUE THREAD

**Issue by eliagentili** [jepiqueau/capacitor-video-player#20]
Is there any way to destroy all the listeners attached to a player?

I have this problem.

I have a few different pages, and in everyone, I have one or more players. Sometimes (tested on Android) it happens that even if I close the video or click the back button the video still playing. I solve adding in the `ionViewWillLeave` a call to `this._videoPlayer.stopAllPlayers();`, but this only put the player in stop instead of destroying it.

For example, in a web page, if I play a video, then put the player in the picture in picture mode and then go back an trigger the `ionViewWillLeave` function, the video still stay in pip and eventually (if I click) playing.

I also notice that on Android, the video doesn't start in fullscreen.

**Comment by jepiqueau** [comment]
@eliagentili I assume that you are working with the Web part of the plugin?

**Comment by jepiqueau** [comment]
@eliagentili which release of the plugin are you working with ?

**Comment by eliagentili** [comment]
I work with all the versions:
- web
- android
- ios

This is the package installed:
"capacitor-video-player": "^2.1.0",

**Comment by jepiqueau** [comment]
@eliagentili It is related with the use of picture-in-picture mode. i never tested with that mode. So what behavior are you  looking for ? When the mode picture-in-picture is activated 
 - the mode fullscreen should be switch-off, 
 - when the video reach the end the mode picture-in-picture should be removed and the listeners destroyed
 - when you exit the video the mode picture-in-picture should be removed and the listeners destroyed

When you said you worked with all the versions do your app is a pwa or it is a native app ?

**Comment by jepiqueau** [comment]
@eliagentili Can you share one of your pages where you have one player and one page where you have several players?

**Comment by eliagentili** [comment]
Ok, I've found that the problem on Android happened because of this line in the `MainActivity.java`. Now, after putting it right it works well:
`add(CapacitorVideoPlayer.class);`

For iOS, when you say in the readme "Modify the Podfile under the ios folder as follows" what do you mean?

Do you mean to remove this line? `pod 'CapacitorVideoPlayer', :path => '../../node_modules/capacitor-video-player'`

Because this is my pod file:

```
platform :ios, '11.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorVideoPlayer', :path => '../../node_modules/capacitor-video-player'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  pod 'CordovaPluginsStatic', :path => '../capacitor-cordova-ios-plugins'
  # Do not delete
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end
```

For the Picture in Picture, I try to record a video.

**Comment by jepiqueau** [comment]
@eliagentili Your pod file is correct, in Android you must add `add(CapacitorVideoPlayer.class);` otherwise it used the web plugin. When you are on iOS and Android there is no Picture-in-Picture mode accessible so i assume the question is for the Web plugin. How do you do to try recording a video as the plugin does not offer this capabilities?

**Comment by eliagentili** [comment]
I record my screen to show you the poblem with picture in picture.

Here you can see it:
[https://www.dropbox.com/s/kdmmzfj22lthljm/test.mp4?dl=0](https://www.dropbox.com/s/kdmmzfj22lthljm/test.mp4?dl=0)

**Comment by jepiqueau** [comment]
@eliagentili Yes i understand when i close a video or reach the end if the picture-in-picture mode was selected i have to close it first and after exit the video which will remove the listener, i will have a look how to to this and come back to you for testing. Thanks anyway for using the plugin, seems you are the first to use the PiP

**Comment by jepiqueau** [comment]
@eliagentili this should be fixed in the new beta release **capacitor-video-player 2.3.0-beta.4** tell me if you have still some issues

**Comment by jepiqueau** [comment]
@eliagentili Any news?

**Comment by jepiqueau** [comment]
@eliagentili as i didn't hear anything from you, i assume that everything is working find now so i close the issue
