### ISSUE TITLE
RemoteEmbeddedPlayer error on Android

### ISSUE THREAD

**Issue by zanuka** [jepiqueau/capacitor-video-player#21]
I can get this plugin to work on iOS, but on Android I get the following: 
```
YouTubeAndroidPlayerAPI: Embed config is not supported in RemoteEmbeddedPlayer
```

**Comment by jepiqueau** [comment]
@zanuka YouTube video link are not supported in the capacitor-video-player plugin. Can you share with me the link of the video you want to play?

**Comment by jepiqueau** [comment]
@zanuka Any news ?
