### ISSUE TITLE
Support for ionic react

### ISSUE THREAD

**Issue by ashutoshsingh0223** [jepiqueau/capacitor-video-player#24]
Is react with ionic supported? If yes are there any examples? I tried modifying the angular code. Couldn't get it to work.

Any hints/help would be very appreciated

**Comment by jepiqueau** [comment]
@ashutoshsingh0223 First thanks for using the plugin, i do not have an app starter ready for Ionic/React yet. I will come back next week with that app ready, it required that i develop the `react-video-player-hook` module, that was in my plan but i was busy with the @capacitor-community/sqlite plugin. Hope you can wait for it

**Comment by ashutoshsingh0223** [comment]
No problem. I will try it out whatever it's ready. Somehow the Cordova plugin I am using keeps on presenting with some problems in ionic-react.

Thanks a lot

**Comment by jepiqueau** [comment]
@ashutoshsingh0223 it has been quite long, but quite few things had to be rewritten. hope you will enjoy. application starter is  https://github.com/jepiqueau/react-video-player-app-starter and you should work with `capacitor-video-player@2.3.1-2` and `react-video-player-hook@0.0.1`

**Comment by ashutoshsingh0223** [comment]
Thanks a lot

**Comment by jepiqueau** [comment]
@ashutoshsingh0223 Thanks, that is the first release, i may change few things in the future to enhance the code as using React.FC with Hooks it's quite new for me and should be improved. i close the issue

**Comment by ashutoshsingh0223** [comment]
Yes. Should move to functional complements slowly.

**Comment by ashutoshsingh0223** [comment]
I reopened it by mistake. Please close this
