### ISSUE TITLE
Any plans to support embedding on iOS and Android

### ISSUE THREAD

**Issue by elskwid** [jepiqueau/capacitor-video-player#26]
Hi @jepiqueau! 

Thank you for a great plugin. We are evaluating using your library for a client project and require that videos be embedded on the iOS and Android platforms - with the ability to enter fullscreen mode from there.

Do you have any plans to add support for this? We're open to talking about potentially sponsoring this work as well. 😄 

Thanks again!

**Comment by jepiqueau** [comment]
@elskwid You have to be more specific, 
 - Is it for PWA apps?  in that case there is already an "embedded" mode for web platform and you can run the PWA app on all platforms ( Web, iOS, Android).
 - Is it for Native apps? in that case it is not easy as you must access the capacitor view controller meaning that is a complete view that you have to define. In that case you could provide a title, a video block with predefined size and a content and this is feasible, you can also define a list of cards having each having each a title, a video block with predefined size and a content this can also be done but only one video will be playing at a time and for sure if you double click on the video it can open fullscreen, this could be also possible the problem will be to keep synchronize the video when going from embedded mode to fullscreen to embedded mode.
Can you tell me what you are looking for ?

**Comment by elskwid** [comment]
@jepiqueau Thanks for the response.

This would be for native apps. We have an entertainment application built and submitted to the various app stores using Ionic React.

In terms of how it's used, we're only ever playing a single video per view, so there is no need to display multiple videos. It's currently using the native players on iOS and Android, which are able to display small, "embedded" video and allow the user to tap to open fullscreen on both players.

The application flow is much like a traditional blog:

* [view] List of posts
* User taps a single post
* [view] Single post
    * Post Header
    * Header Image
    * Video, if present on the post
* User taps video controls and plays the video
* User can use native video controls to view the video fullscreen (and other features)
* User can exit fullscreen and the video returns to the same position on the post

Does that help explain what we're doing?

**Comment by jepiqueau** [comment]
@elskwid So it is the View Single Post that you would like to have in native. I mean that you have a Ionic/React Page showing the List of posts and when the user select one post out of the list the single post view is build up directly in native. so you will have to specify the format of this page Post Header size (top, left, width, height) and the text size and font (fonts are different in iOS than in Android), Header image size and position and Video size and position. in fact the image and the video could be superimposed, when the page is opened the user see the image if it click on the video start and if it double click, the video goes full screen. i have got the bit and pieces to do this on Android it works fine on iOS the video restart when the user click fullscreen that was it was not yet released. Is my understanding correct.

**Comment by elskwid** [comment]
@jepiqueau Only the video player is actually native. We don't build up any views in native - our views are the Ionic Hybrid views - meaning, we have a React component hierarchy with a node using the `<video>` tag, which relies on the native players on iOS and Android.

We're currently just letting the devices do what they want to do with the video, which is in `m3u8` format.

Does that make sense?

**Comment by jepiqueau** [comment]
@elskwid No it doesn't, i do not understand how from the <video> tag you call the `capacitor-video-player` Have you look at `https://github.com/jepiqueau/react-video-player-app-starter` which demonstrates how to use the player.

**Comment by jepiqueau** [comment]
@elskwid Any news ?

**Comment by pankajcodealchemy** [comment]
@jepiqueau Thank you for a great plugin, is there any updates on this issue, in my native apps(iOS/android) video is not play in embedded mode, so have you plan to support embedding in iOS and Android native?

**Comment by juanico18** [comment]
@pankajcodealchemy @elskwid Have you reached any progress on this?
The point to be able to play video embedded I think would be use a video javascript library that allow to play hls video using the <video> tag. 

I want to review if it is possible to integrate videojs for example to play hls videos in iOS and android.
