### ISSUE TITLE
Any plans to add Chromecast support

### ISSUE THREAD

**Issue by elskwid** [jepiqueau/capacitor-video-player#27]
Hi @jepiqueau!

As I mentioned in #26, we're evaluating this library for a client project. One of the requirements is to be able to use Chromecast to play the videos (at least on Android).

Have you thought about adding Chromecast support at all? It looks like ExoPlayer has a Chromecast plugin but we're not sure about iOS support. We would be open to sponsoring this work if you're interested.

Thank you for a great plugin!

**Comment by jepiqueau** [comment]
@elskwid I do not have any plans, i am not familiar with the Chromecast technology. it would also be difficult to test as i do not have a physical iOS device and i am not sure that we can test this from a simulator

**Comment by jepiqueau** [comment]
@elskwid i look a bit at this for android it seems to be feasible (not all the video types work well). you need in fact to have two players one standard ExoPlayer as now and one CastPlayer so when it cast to the TV the video is not running any more on the device. We will have to see how this could work through the capacitor bridge

**Comment by jmellicker** [comment]
@elskwid Did you ever find a Chromecast solution?

We are also interested in adding Chromecast support to this project, we would be happy to sponsor or co-sponsor the project financially.

Here are some links that might be helpful:

### iOS

- [https://developers.google.com/cast/docs/ios_sender](https://developers.google.com/cast/docs/ios_sender)
    - [https://github.com/googlecast/CastVideos-ios](https://github.com/googlecast/CastVideos-ios)
    - [https://cocoapods.org/pods/google-cast-sdk](https://cocoapods.org/pods/google-cast-sdk)

### Android

- [https://developers.google.com/cast/docs/android_sender](https://developers.google.com/cast/docs/android_sender)
    - [https://github.com/googlecast/CastVideos-android](https://github.com/googlecast/CastVideos-android)
- [https://www.nodesagency.com/google-cast/](https://www.nodesagency.com/google-cast/)

**Comment by jepiqueau** [comment]
@jmellicker it is not an easy process and difficult to test i try the last 2 days to use some of the demo apps on Apple simulator for non identified reason it does not show the google cast button, on android i successfully run the apps with the simple player on my physical device but not on emulator but my plugin use Exoplayer to play the video. On web the demo run well. So if you have an idea on how to test it on Apple as i do not have a physical iphone, feel free to help

**Comment by jmellicker** [comment]
Yes @jepiqueau, we would love to test, we have many iOS devices! Should we watch for a new branch, or...?

**Comment by jepiqueau** [comment]
@jmellicker for the time being i stopped working on that one as i do have to maintain others of my plugins `@capacitor-community/sqlite` & `@capacitor-community/photoviewer` i will tell you when i will look again. Thanks for your understanding.

**Comment by jepiqueau** [comment]
@elskwid @jmellicker Finally this is now available in 3.7.3 So i close the issue
