### ISSUE TITLE
Is there way to configure nodownload option on this plugin?

### ISSUE THREAD

**Issue by vijayt27** [jepiqueau/capacitor-video-player#31]
Hi, thanks for this plugin, its really good. Worked well for our hybrid app which we are trying using ionic/angular and capacitor.

We are trying to prevent the "download" option from the video, looks like there is a way from video element to add below tag

`controlsList="nodownload"`

Is there an easy to set this as property or configure when we use "this.videoPlayer.initPlayer".

Appreciate any help on this.

Thanks,
Vijay

**Comment by jepiqueau** [comment]
@vijayt27 i will have a look

**Comment by vijayt27** [comment]
> @vijayt27 i will have a look

@jepiqueau - Thanks, I do have one workaround on this, added below js code after the initplayer. It works fine for my usecase.

`document.querySelector('video').setAttribute('controlsList', 'nodownload');`

**Comment by jepiqueau** [comment]
@vijayt27 i come back on the maintenance of this plugin after a long period working on the refactor of `@capacitor-community/sqlite`. Are you looking for this `nodownload` for the Web and/or Electron  platforms not for native ones (Android, iOs)?
