### ISSUE TITLE
Screen falling asleep

### ISSUE THREAD

**Issue by lapamplemousse** [jepiqueau/capacitor-video-player#33]
My screen is falling asleep while the video is playing. So I have to keep touching it to keep the screen bright and prevent it from turning off al together. are there any fixes for this?

**Comment by jepiqueau** [comment]
@lapamplemousse which platform ? after how long of the video playing it is happening? Is it not a parameter to set in your device?

**Comment by jepiqueau** [comment]
@lapamplemousse Did you solve this ? if yes can you close the issue

**Comment by lapamplemousse** [comment]
Sorry I did not see your reply. I have only tested it on android. It will fall asleep with whatever time I have set my screen to fall asleep with inactivity in the android settings. 

So If I have it in my settings the screen should fall asleep with 30 seconds of inactivity, I will have to touch my screen every thirty seconds to watch the video.

**Comment by jepiqueau** [comment]
@lapamplemousse Did you look at the optimize settings for battery `https://www.youtube.com/watch?v=7iPVNN3ZxWw`

**Comment by lapamplemousse** [comment]
Yes I have mine set to one minute. but I would have thought a video player should ignore this as you are using the screen. you are playing a video.

**Comment by jepiqueau** [comment]
@lapamplemousse i will try to dig out and find something. I currently busy in the refactor of `@capacitor-community/sqlite` plugin so i will look at this after. Thanks for your patience

**Comment by jepiqueau** [comment]
@lapamplemousse Thank for your patience, the refactor of `@capacitor-community/sqlite` plugin took me more time that i thought. This issue should be solved in release 2.4.5-1 of the plugin. Tell me if it works on your side.

**Comment by jepiqueau** [comment]
@lapamplemousse As you did not come back i close the issue
