### ISSUE TITLE
Add a back arrow on the top left would be better when the screen is landscape.

### ISSUE THREAD

**Issue by LiLeiAndroid** [jepiqueau/capacitor-video-player#35]

**Comment by jepiqueau** [comment]
@LiLeiAndroid you mean on the web platform?

**Comment by LiLeiAndroid** [comment]
@jepiqueau on android platform.

**Comment by jepiqueau** [comment]
@LiLeiAndroid On android platform you have to use the back press button

**Comment by LiLeiAndroid** [comment]
@jepiqueau  Now more and more people use the full screen and hide the physical back button. If you add a back button on the top of the controller view, there would be a better user experience, just a suggestion😁

**Comment by jepiqueau** [comment]
@LiLeiAndroid ok thanks for the suggestion. I will have look to see how it is feasible for the next release. These days, I am too busy in the refactor of @capacitor-community/sqlite plug-in to distract myself from it. I will keep you in touch when done thanks for your patience

**Comment by LiLeiAndroid** [comment]
@jepiqueau no problem, good luck!

**Comment by jepiqueau** [comment]
@LiLeiAndroid I am back, this is solved in the release 2.4.5-2 of the plugin

**Comment by jepiqueau** [comment]
@LiLeiAndroid As you did not come back i close the issue
