### ISSUE TITLE
 capacitor-video-player aspect ratio fill

### ISSUE THREAD

**Issue by AnasProgrammer2** [jepiqueau/capacitor-video-player#39]
Hello 
how to add button or make video play with aspect ratio fill

**Comment by jepiqueau** [comment]
@AnasProgrammer2 I do not understand what do you mean by aspect ratio fill. A video has it own size and it displayed according to its size

**Comment by AnasProgrammer2** [comment]
> @AnasProgrammer2 I do not understand what do you mean by aspect ratio fill. A video has it own size and it displayed according to its size

hello , thanks for reply 
now when play video , i can't find button ( fill the screen)  ,
![alt text](<a href="https://ibb.co/W2Xdc8d"><img src="https://i.ibb.co/4VLDjvD/Whats-App-Image-2021-03-22-at-6-28-31-PM.jpg" alt="Whats-App-Image-2021-03-22-at-6-28-31-PM" border="0"></a>)

**Comment by jepiqueau** [comment]
@AnasProgrammer2 what is the size of the video. Can you give me the link to that video?

**Comment by AnasProgrammer2** [comment]
> @AnasProgrammer2 what is the size of the video. Can you give me the link to that video?

hello , what i mean like that button in default ios player ( fill the screen )

<a href="https://ibb.co/fDKVPMY"><img src="https://i.ibb.co/KKQc36j/Whats-App-Image-2021-03-30-at-8-59-05-PM.jpg" alt="Whats-App-Image-2021-03-30-at-8-59-05-PM" border="0"></a>

<a href="https://ibb.co/FHwx37S"><img src="https://i.ibb.co/qJsyj1t/Whats-App-Image-2021-03-30-at-8-58-57-PM.jpg" alt="Whats-App-Image-2021-03-30-at-8-58-57-PM" border="0"></a>
>

**Comment by jepiqueau** [comment]
@AnasProgrammer2 This button works fine on iOS, so i assume your question was relative to android. Try to be clearer in your description of the issue. I use the players as they come by default. So iOS AVPlayer got that feature and Android Exoplayer do not have that feature implemented. So you will not find it in Android or on Web platform.
