### ISSUE TITLE
FR: embedded video player

### ISSUE THREAD

**Issue by mburger81** [jepiqueau/capacitor-video-player#4]
Hello, at first nice plugin,

we tested your video player first on web, and we see do you always create a new video element always in fullscreen mode. 

In this way we can not use embedded videos, like multiple videos on one screen.

We think you could use capVideoPlayerOptions to pass an already existing video element? What do you think about it?

Not sure, we are not an expert on android/ios, but how is it on native system? Is there possible to use native video player for multiple videos on the same screen, like youtube?

**Comment by jepiqueau** [comment]
Interesting comment, I may look at it but in that case I will create a new plugin for multiple videos

**Comment by mburger81** [comment]
Why would you like do this.
On web you can have many video tags with many instances, no problem about that. 

Not sure how on Android/iOS

But I think it's better to don't have different plugin there is probably no need for it. If you have to plugins you also have to maintain both.

**Comment by mburger81** [comment]
@jepiqueau hey is there any plans for this?

**Comment by jepiqueau** [comment]
Not really what you would like to have ? Do you want to provide a list of videos to play and have each video displayed in a cell of a grid with a maximum of 4 videos on the screen and having the possibility to swap the videos by selecting new one from a thumbs gallery slider ? Before i start looking at something i need more data from you

**Comment by jepiqueau** [comment]
Ok, feel free to come back

**Comment by es-daniel** [comment]
@jepiqueau can I use a link like this `https://www.youtube.com/embed/34fDUKaJBtw ` with this plugin?

**Comment by jepiqueau** [comment]
@es-daniel No you cannot in this release, it is not a youtube player, you may use ```https://www.npmjs.com/package/capacitor-youtube-player``` provided by someone else.

**Comment by pnaylor** [comment]
Definitely interested in being able to embed the plugin player as a video element on a page that the user can then interact with more persistently than the popup style player that disappears from the page when closed, as in demo.

That being said, this looks like a great start and thank you!

**Comment by jepiqueau** [comment]
@pnaylor yes would be interesting but any idea on how to define the position on the page and the size of the video and would you like to embed several video player on the same page. if you specify more precisely your needs, i may have a look to propose fullscreen option or embedded option. waiting for your reply

**Comment by pnaylor** [comment]
Glad to hear there is interest in expanding this functionality @jepiqueau !

Hm, if it was embedded in an html5 video element then wouldn't all of those properties (height/width) already be encapsulated within the element and where it was added to page or how it was styled?

My current needs would be either the ability to have multiple videos embedded but only one visible at a time or one video/player element embedded that was able to update it's video source dynamically, so a user could select from a list of videos and have their selection loaded into the same player.

Thanks, best!

**Comment by jepiqueau** [comment]
@mburger81  @pnaylor Embedded videos for the web plugin have been added to capacitor-video-player@1..1.3-3 see ```https://www.npmjs.com/package/capacitor-video-player```  and ```https://github.com/jepiqueau/ionic-capacitor-video-player``` for a ionic implementation. the Viewme and the PWA app implementation have not been updated yet. Can you test the new plugin, waiting for comments  and will have a look at the IOS & Android implementation but it seems not straightforward

**Comment by pnaylor** [comment]
This looks amazing @jepiqueau thank you! Would love to see the stencil demo updated with it as well if you get a chance.

Will share further feedback after trying it out.

Best

**Comment by jepiqueau** [comment]
this is going to be deprecated visit @jeepq/capacitor for new release

**Comment by pnaylor** [comment]
Ah, thank you for the update. Doesn't seem to exist yet though, https://github.com/jepiqueau/capacitor?
Appreciate your help!

**Comment by jepiqueau** [comment]
@pnaylor  look at  doc  at ``` https://github.com/jepiqueau/jeep/blob/master/capacitor/plugins-library/docs/VideoPlayer.md ``` to install it  ``` npm install --save @jeepq/capacitor@latest ```
