### ISSUE TITLE
add cc subtitle to video 

### ISSUE THREAD

**Issue by AnasProgrammer2** [jepiqueau/capacitor-video-player#40]
hello , how to add subtitle to video ? (ios , Android)

**Comment by AnasProgrammer2** [comment]
any update ?

**Comment by jepiqueau** [comment]
@AnasProgrammer2 Can you provide a link to a video and a link to a subtitle.vtt file for testing purpose

**Comment by jepiqueau** [comment]
@AnasProgrammer2 Which OS Android, iOS, Web first ?

**Comment by jepiqueau** [comment]
@AnasProgrammer2 Which subtitle format?

**Comment by AnasProgrammer2** [comment]
Hello 
Is CC subtitle ( srt or VTT)
In android your plugin use expplayer
And exoplayer is supported subtitle 

https://medium.com/@kidkodindia/showing-subtitles-lyrics-on-android-exoplayer-98a88a7b53b2


And in ios your plugin

https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/selecting_subtitles_and_alternative_audio_tracks

**Comment by AnasProgrammer2** [comment]
> @AnasProgrammer2 Which OS Android, iOS, Web first ?

I create my app for ios and android

**Comment by AnasProgrammer2** [comment]
> @AnasProgrammer2 Can you provide a link to a video and a link to a subtitle.vtt file for testing purpose

Can you use any subtitle movies you need
https://subscene.com/browse/popular/all/1

**Comment by jepiqueau** [comment]
@AnasProgrammer2 This has been fixed for Android platform with release 2.4.7-1. Demonstrated in https://github.com/jepiqueau/angular-videoplayer-app-starter.git. Tell me if it works on your side. I will start looking for implementation in iOS.

**Comment by AnasProgrammer2** [comment]
> @AnasProgrammer2 This has been fixed for Android platform with release 2.4.7-1. Demonstrated in https://github.com/jepiqueau/angular-videoplayer-app-starter.git. Tell me if it works on your side. I will start looking for implementation in iOS.

thanks man , i will test it  then inform you

**Comment by AnasProgrammer2** [comment]
Any update please

**Comment by jepiqueau** [comment]
fix in release 2.4.7-2
