### ISSUE TITLE
Change subtitle text color

### ISSUE THREAD

**Issue by AnasProgrammer2** [jepiqueau/capacitor-video-player#42]
Hello 
How to change font-style / size / color / background color of subtitle (android)

**Comment by jepiqueau** [comment]
@AnasProgrammer2 You already ask for it in #40 so no need to ask again. It is done but it will be issued in the meantime that the implementation in the iOS plugin. So be patient

**Comment by jepiqueau** [comment]
@AnasProgrammer2 fix in release 2.4.7-2
