### ISSUE TITLE
 Invalid platform: @capacitor-community/electron

### ISSUE THREAD

**Issue by marfrede** [jepiqueau/capacitor-video-player#43]
```
$ npx cap sync @capacitor-community/electron
[error] Invalid platform: @capacitor-community/electron
```

**Comment by jepiqueau** [comment]
@marfrede from your app remove the electron folder and run the following
```bash
npx cap add @capacitor-community/electron
npm run build
npx cap copy @capacitor-community/electron
npx cap open @capacitor-community/electron
```
After this it should work, if not send me your package.json file

**Comment by marfrede** [comment]
Wow, thanks for the quick answer!

I wonder wether this step is necessary at all, when developing for android and ios only?

**Comment by jepiqueau** [comment]
@marfrede You do no need these steps if you develop only for iOS and Android
