### ISSUE TITLE
Player not playing Base64 video urls

### ISSUE THREAD

**Issue by alfredoalfa** [jepiqueau/capacitor-video-player#49]
When i try to play a base64 video url on ios the plugin doesn't play it and the console send this error "file Path not implemented" but the url path is implemented with a base64.

<img width="878" alt="Captura de Pantalla 2021-09-03 a la(s) 3 08 57 p  m" src="https://user-images.githubusercontent.com/10062965/132055105-af95061f-b765-496c-ad02-c00fb104ca19.png">

error log:
⚡️  To Native ->  CapacitorVideoPlayer initPlayer 36994010
⚡️  TO JS {"result":false,"method":"initPlayer","message":"filePath not implemented"}

npm version:
->     v12.18.3
default -> 12.18.3 (-> v12.18.3)

angular version:
Angular CLI: 9.1.9
Node: 12.18.3
OS: darwin x64

Angular: 9.1.11
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.9
@angular-devkit/build-angular     0.901.9
@angular-devkit/build-optimizer   0.901.9
@angular-devkit/build-webpack     0.901.9
@angular-devkit/core              9.1.9
@angular-devkit/schematics        9.1.9
@angular/animations               9.1.12
@angular/cdk                      9.2.4
@angular/cli                      9.1.9
@angular/fire                     6.0.2
@angular/material                 9.2.4
@ngtools/webpack                  9.1.9
@schematics/angular               9.1.9
@schematics/update                0.901.9
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

ionic version:
5.4.16

plugin version:
capacitor-video-player (2.4.7)

Appreciate any help on this.

Thanks.

**Comment by jepiqueau** [comment]
@alfredoalfa Hi thanks for using the plugin. I think the title of the issue is wrong it should be something around this `Player not playing Base64 video urls` i do not think it is specific to iOS. Nowhere in the documentation you will find that the plugin is playing Base64 video urls.  So it should not be an issue as such but a software enhancement. Could you give me an example of where i can find Base64 video urls on the net so i may have a look on how much work is related to implement this new feature.

**Comment by alfredoalfa** [comment]
@jepiqueau Hi thanks for your answer, we are working on an example of playing base64 video url that you can use to test this behavior.

**Comment by jepiqueau** [comment]
@alfredoalfa tell me when it is ready

**Comment by alfredoalfa** [comment]
@jepiqueau  Hi, we decided to don't use  base64 video URL, thanks for all your help.

**Comment by jepiqueau** [comment]
@alfredoalfa I was trying to implement it I did it for the Web it works well but take a lot of time to create the base64 Video. I have not test it for android and iOS Web.  So if you do not need it I will stop on this

**Comment by alfredoalfa** [comment]
@jepiqueau I really thank you for all your work, but we decided to don't use base64 video, so you can stop what you are doing.

**Comment by jepiqueau** [comment]
👍
