### ISSUE TITLE
How to get video player to autoplay

### ISSUE THREAD

**Issue by louisnelza** [jepiqueau/capacitor-video-player#50]
Hi there, love this plugin!

I'm trying to get the video to autoplay. According to the browser rules it has to be muted.

Trying the regular old JS way but still getting blocked.

```
 let video = document.querySelector('video');
      video.defaultMuted = true;
      video.autoplay = true;
```

Is there a plugin-specific way to do this?

Thanks

**Comment by jepiqueau** [comment]
@louisnelza unfortunately there is no way so you have to un-muted when it is starting to play. At the early version of the plug-in ` video.defaultMuted  = true` was working but is not anymore you cannot infringe the browser rules

**Comment by louisnelza** [comment]
Thanks for the feedback @jepiqueau!
