### ISSUE TITLE
Setting authorisation header

### ISSUE THREAD

**Issue by pedramp20** [jepiqueau/capacitor-video-player#52]
I am trying to play a HLS video (m3u8) which requires credentials (signed cookies). Is there a way to set the authorisation header of the xhr when initialising or playing the video player?

**Comment by jepiqueau** [comment]
@pedramp20  thanks for using the plugin. Your question is for which platform (android, iOS, web browser) ?

**Comment by pedramp20** [comment]
@jepiqueau  iOS.

**Comment by jepiqueau** [comment]
@pedramp20 Any progress from your side or i will close the issue

**Comment by tsenguunchik** [comment]
Any development on this front? I'm also trying to play video on ios with authorization header. Either query parameter or cookie header.
