### ISSUE TITLE
Background mode 

### ISSUE THREAD

**Issue by ramses512** [jepiqueau/capacitor-video-player#53]
Can the background mode be implemented for IOS?

**Comment by jepiqueau** [comment]
@ramses512 i think what you are asking is more the picture-in-picture mode. I will look at it and depending on the complexity i will decide if it may be implemented

**Comment by jepiqueau** [comment]
@ramses512 in the release3.3.1-1 the Picture in Picture mode has been added to the Android Plugin. Can you test it and tell me if it is what you were looking for. Enjoy it

**Comment by ramses512** [comment]
> @ramses512 in the release3.3.1-1 the Picture in Picture mode has been added to the Android Plugin. Can you test it and tell me if it is what you were looking for. Enjoy it

I need for IOS thanks you!

**Comment by jepiqueau** [comment]
@ramses512 release 3.3.2 implement PiP for Android and iOS Come back to me when tested

**Comment by jepiqueau** [comment]
@ramses512 Have you test it? i spent a lot of time to make it working on iOS so i hope you will look at it. Without answer from your side i will close the issue

**Comment by ramses512** [comment]
Working fine, thanks!
