### ISSUE TITLE
Play videos from External Storage (storage/emulated/0/) 

### ISSUE THREAD

**Issue by TekiLakshmanSundeep** [jepiqueau/capacitor-video-player#54]
@jepiqueau  In my application i am storing video files in External storage which is in `storage/emulated/0/Android/data/PACKAGE_NAME/files/my_folder/1.mp4`. I need to play the 1.mp4 using this capacitor-video-plugin version 3.0. So far i got to know that it can play videos from internal storage. Is there any support to play the content from external storage ?

**Comment by jepiqueau** [comment]
@TekiLakshmanSundeep fix in 3.3.0-1 i got an example `file:///storage/extSdCard/DCIM/Camera/jellies.mp4` in [angular-videoplayer-app-starter](https://github.com/jepiqueau/angular-videoplayer-app-starter). Check if it is working for you

**Comment by jepiqueau** [comment]
@TekiLakshmanSundeep Did you test it?

**Comment by TekiLakshmanSundeep** [comment]
@jepiqueau Nope.. I'll check it and get back to you.

**Comment by jepiqueau** [comment]
@TekiLakshmanSundeep 👍

**Comment by jepiqueau** [comment]
@TekiLakshmanSundeep Ok so i close the issue
