### ISSUE TITLE
Play from folders inside Application Folder

### ISSUE THREAD

**Issue by mamane10** [jepiqueau/capacitor-video-player#55]
@jepiqueau Good morning.
In my case, i have to play videos from application storage `application/files/OTHER/FOLDERS/video.mp4` which obviously throws:

>  'initPlayer command failed: Video file not found' 

To fix this issue, the line 22 in FileUtils: 
`path = filesDir + url.substring(url.lastIndexOf('/') + 1);`
Should be like this:
`path = filesDir + url.substring(url.lastIndexOf("files/") + 6);`

Can this be fixed anytime soon?
Thanks in advance.

**Comment by jepiqueau** [comment]
@mamane10 thanks for your patience and sorry for the delay. this has been fixed in 3.2.5

**Comment by mamane10** [comment]
Alright, Thank you

**Comment by yelhouti** [comment]
this is also fixed by: https://github.com/jepiqueau/capacitor-video-player/pull/57
