### ISSUE TITLE
DCIM folder as URL-Path

### ISSUE THREAD

**Issue by waberger** [jepiqueau/capacitor-video-player#56]
Is it possible to play videos from the Android DCIM folder? I can't get the path to work.

**Comment by jepiqueau** [comment]
@waberger thanks for looking at the plug-in. Can you please be more specific on which folder do you want to have access. If it is the media folder use 'internal'

**Comment by jepiqueau** [comment]
@waberger Is it any DCIM folder on internal and/or external?

**Comment by waberger** [comment]
@jepiqueau it's internal file:/storage/emulated/0/DCIM/Camera/video.mp4

**Comment by jepiqueau** [comment]
@waberger if you set the url to 'internal' you will get the list of all videos  stored on your device internal and external storage. Can you test it and revert to me.

**Comment by jepiqueau** [comment]
@waberger i tested on physical device it works, on emulator it doesn't seem to work

**Comment by waberger** [comment]
internal as url inside the initPlayer method? Or how do i get a list of all videos

**Comment by jepiqueau** [comment]
@waberger yes, look at angular-videoplayer-app-starter there is an example

**Comment by jepiqueau** [comment]
@waberger Any progress on this?

**Comment by yelhouti** [comment]
@jepiqueau I face a similar problem, made a PR: https://github.com/jepiqueau/capacitor-video-player/pull/57
