### ISSUE TITLE
Is there any way to play the WebRTC streams ?

### ISSUE THREAD

**Issue by TekiLakshmanSundeep** [jepiqueau/capacitor-video-player#62]
Any support to play the WebRTC media streams or tracks ??

**Comment by jepiqueau** [comment]
@TekiLakshmanSundeep Is it for Web plugin only? Can you be more specific on what you want to achieve I do nto know anything about WebRTC

**Comment by TekiLakshmanSundeep** [comment]
@jepiqueau, It's for mobile plugin. Regarding WebRTC It's a real-time communication capabilities to your application that works on top of an open standard. It supports video, voice, and generic data to be sent between peers, allowing developers to build powerful voice- and video-communication solutions. The technology is available on all modern browsers as well as on native clients for all major platforms. The technologies behind WebRTC are implemented as an open web standard and available as regular JavaScript APIs in all major browsers. 

For more info please check this url:[ https://webrtc.org/ ]( https://webrtc.org/ )and [https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API )

In simple words it's a protocol which will be used to stream the audio or video content from one peer to another peer in the browser based applications.

My requirement is like currently i'm sending media stream content from a source to my mobile application now i want to play the content  in my mobile application. Currently i'm achieving it with html <video> tag but i want to play with the mobile supported video player

**Comment by jepiqueau** [comment]
@TekiLakshmanSundeep This must be done on a dedicate capacitor plugin. So i close the issue
