### ISSUE TITLE
Question: Is this just a HTML5 player when used in Electron?

### ISSUE THREAD

**Issue by fjeddy** [jepiqueau/capacitor-video-player#64]
It's not mentioned anywhere (Or I can't find it), but this is just a HTML5 player when used with Electron? It will only support the common web-formats like mp4, webm and ogg?

**Comment by jepiqueau** [comment]
@fjeddy Thanks to look at the plugin. In Electron it is the web plugin which is used it as the standard web-formats plus the hls format through the use of hls.js
