### ISSUE TITLE
Question: How to set Embedded model on ios and android?

### ISSUE THREAD

**Issue by lixunyi** [jepiqueau/capacitor-video-player#65]
I am very grateful to your team for providing such an excellent playback component. At present, due to the need for Embedded model in IOS and android platform, after looking at the documentation carefully and using the use case, we find that this feature has not been implemented on the native platform, so I would like to ask what is the reason why this feature cannot be supported? 
Looking forward to your reply, thank you.

**Comment by jepiqueau** [comment]
@lixunyi thanks for using the plug-in. The simple answer is that I did not find the way after many trials how to do it with capacitor. I may have another look if you have some suggestions they will be welcome

**Comment by lixunyi** [comment]
@jepiqueau 
Thank you for your reply. The previous question stems from my lack of understanding of the way ionic native interacts. 
Our current requirement is to display the video player in ionic as in web, but I have tried and found that the video tag of the player will not be created dynamically as long as it is detected in a platform such as ios. 
If only this restriction could be removed, it would be great to be able to provide video playback in the form of html5, whether on a mobile platform or not.

**Comment by jepiqueau** [comment]
@lixunyi i look back. You can do this in a PWA app which will use the Web part of the plugin and the PWA app will run on iOS and/or Android. As native app iOS or Android the capacitor bridge present a view controller as an entire page so we could use a transparent background color for that native page that let you see your app page but nothing of that app page will be accessible for action. So i do not think it is worth to do the work. I am sorry for this.
