### ISSUE TITLE
feature request > speed control

### ISSUE THREAD

**Issue by jmellicker** [jepiqueau/capacitor-video-player#67]
A feature that would be useful is the ability for a user to select from a menu of preset speeds for video playback.

Our proposal would be to offer .25, .5, .75, 1x (normal speed), 2x, and 4x.

We forked this plugin a while ago and hired a developer to add some features (for iOS only). The fork is here: [https://github.com/platformpurple/capacitor-video-player-plugin](https://github.com/platformpurple/capacitor-video-player-plugin)

Unfortunately we have the impression that the code in this fork is probably a mess and not a good foundation to build on. (Maybe @jepiqueau could look it over and let us know for sure, we are not Swift developers so we're not sure.)

But one feature that was added was a simple video speed control, it seems to work fine in the forked plugin, so maybe it is possible to "steal" some code from this fork?

**Comment by jepiqueau** [comment]
@jmellicker i already answer that one on November 11, see issue#60

**Comment by jmellicker** [comment]
@jepiqueau it looks like [issue#60 ](https://github.com/jepiqueau/capacitor-video-player/issues/60)is about adding a selector for different video resolutions, I was proposing a speed control, so the user could play the video faster or slower.

We are happy to sponsor this feature financially if anyone is interested!

**Comment by jepiqueau** [comment]
@jmellicker methods `setRate(rate)` and `getRate()`have been added in release 3.4.0-2 rate can be in `[0.25,0.5,0.75,1.0,2.0,4.0]` hope this will help you i looked quickly to the fork but it was quite messy so i just google and find the way. thiese methods have been added to the iOS, Android and Web part of the plugin. Enjoy it

**Comment by jmellicker** [comment]
@jepiqueau this is awesome news, we will try it ASAP, merci beaucoup!!
