### ISSUE TITLE
E/Capacitor: Unable to open asset URL: http://localhost/raw/video

### ISSUE THREAD

**Issue by lapamplemousse** [jepiqueau/capacitor-video-player#7]
When I try and play the video in Android studio I am getting the following problem:

When trying to import the capacitor video player, I am getting the following error "Cannot resolve symbol jeep" in the following line in main activity
import com.jeep.plugin.capacitor.videoplayer.CapacitorVideoPlayer;

**Comment by lapamplemousse** [comment]
'npx cap update' fixed it

**Comment by jepiqueau** [comment]
@lapamplemousse  Yeh, you always have to run ```npx cap update ``` when you install a new release of the video player
