### ISSUE TITLE
feat: move exitOnEnd to initPlayer

### ISSUE THREAD

**Issue by bazuka5801** [jepiqueau/capacitor-video-player#74]
Hello! I have a need to leave the video after exit, can we put the parameter in the initialization of the player?

https://github.com/jepiqueau/capacitor-video-player/blob/c3bb39389d3b3185c2bc6f6591866d876f72fb9d/ios/Plugin/CapacitorVideoPlayer.swift#L23-L26

**Comment by jepiqueau** [comment]
@bazuka5801 this has been added in release 3.4.0-3
