### ISSUE TITLE
add cookies to request

### ISSUE THREAD

**Issue by mersal-developing** [jepiqueau/capacitor-video-player#75]
how can i add cookies to hls streaming request in this player?
i am working on android application and ios application

**Comment by jepiqueau** [comment]
@mersal-developing Hi can you explain a bit more. i do not understand what you mean by adding cookies to hls stream.

**Comment by jepiqueau** [comment]
@mersal-developing i google a bit so now i understand. It is not supported yet

**Comment by mersal-developing** [comment]
Thanks for your response

**Comment by jepiqueau** [comment]
@mersal-developing see with the headers if it is working now release 4.1.0

**Comment by jepiqueau** [comment]
@mersal-developing Is that working now? I close the issue feel free to re-open it if needed
