### ISSUE TITLE
On Android, apps exit if you play a video, pause, and then resume the app

### ISSUE THREAD

**Issue by jh-gh** [jepiqueau/capacitor-video-player#77]
Thanks for this great plugin!

I have been using the 2.X version successfully in a Capacitor 2 based app.

I am in the process of upgrading apps to Capacitor 3.  

When I use the current version of this plugin (v3.4.0-4), there is a problem on Android with the following sequence:

- Play a full screen video
- Put the app in the background (doesn't matter if the video is playing or paused)
- Resume the app
- At this point ... **the app immediately exits completely**

You can reproduce this problem using the Angular starter app: https://github.com/jepiqueau/angular-videoplayer-app-starter

I suspect that the problem was introduced with the changes to support PIP on Android.

If I downgrade to the version before the introduction of PIP/Android (3.3.0-1) the problem does not occur (the app resumes successfully).

**Comment by jepiqueau** [comment]
@jh-gh  Can you please be a bit more specific on the behavior
if i open a video fullscreen and tap on the back press the video goes to the PIP mode and here if you press on the home button or on the back press the video continues to play.
if you then close the PIP mode, the video goes back fullscreen, 
- if you press now on back press it goes again in PIP mode
- or if you press on the home button the application exits completely. Would you prefer the application to close the fullscreen? This will require to manage the Home button which i did not find the way to do it
Is this you are asking?

**Comment by jh-gh** [comment]
@jepiqueau Thanks for your reply.
The behaviour occurs any time the user puts the app into the background while it is playing full screen video.  This can be done in different ways.

**User uses home button **
- User starts playing a fullscreen video
- User taps home button (app goes into the background and video pauses)
- User resumes the app (either by tapping the desktop icon to launch it again or selecting it from the recent/running apps)
- At this point, the app is still running and attempts to resume ... however it quickly exits

**User switches between apps with the app switcher **
- User starts playing a fullscreen video
- User uses the app switcher to switch to a different app (app goes into the background and video pauses)
- User resumes the app (either by tapping the desktop icon to launch it again or selecting it from the recent/running apps)
- At this point, the app is still running and attempts to resume ... however it quickly exits
 
The behaviour of both of plugin in both of the scenarios above in version 3.3.0-1 and below (including 2.4.7) is that when the user resumes the app, the app does NOT exit.  Rather, the full screen video page is again displayed, with the video in a paused state where it left off.  The user can then easily tap play to resume playing where they left off.

If you try building the Angular starter app with version 3.3.0-1 of the plugin then you will see this behaviour (which is what I think it should do).

Thanks.

**Comment by jepiqueau** [comment]
@jh-gh Thanks for describing the two processes  in detail, it help me to solve the issue. It is now fixed in release 3.4.0 of the plugin. Feel free to close the issue after tests if it is working

**Comment by jh-gh** [comment]
@jepiqueau Thanks for the quick turnaround!

Your fix appears to work for the scenarios that I described.
However, it seems to have also introduced a new issue with PIP mode on Android as follows:

- Start full screen video
- Tap video so that controls are displayed
- Tap PIP box to enter PIP mode
- Video is shown in small PIP box at the bottom of the screen
- Tap the X in the small PIP box
- PIP window disappears and app appears to have exited
- **However, audio continues to play ... and there seems to be no way to stop it ... or to bring the video window or app back to the foreground.**. The app does not show in the app switcher etc.

In the previous version with PIP (3.4.0-4) tapping the X in the small PIP box would immediately stop the video (and audio) and exit the app (as expected).

Also, would it be possible to add a flag to the options passed to initPlayer e.g. pipEnabled (default true) that would allow apps to opt out of PIP mode?

Thanks.

**Comment by jepiqueau** [comment]
@jh-gh audio issue is fixed in 3.4.1-1 as well as adding the pipEnabled flag in options to initPlayer

**Comment by jh-gh** [comment]
@jepiqueau Looks good.  Thanks for your amazing support! I will close this issue.

Note that while testing this, I did notice a separate issue on iOS that I have raised here: https://github.com/jepiqueau/capacitor-video-player/issues/78

As I mentioned in that issue, that problem also seems to have arisen not with this fix here ... but from versions after 3.3.0-1, thanks.
