### ISSUE TITLE
Fullscreen Android suspend screen and turn off

### ISSUE THREAD

**Issue by juaala** [jepiqueau/capacitor-video-player#79]
Hi, i have a problem with Fullscreen. I want to keep the screen active when the video is playing. it is in full screen but it turns off after a while. Any suggestion? 
The code:

![Captura de pantalla de 2022-03-07 20-36-38](https://user-images.githubusercontent.com/35939185/157105657-e12296e1-c6b7-45f8-8e1b-ffed3e6144bb.png)

![Captura de pantalla de 2022-03-07 20-27-44](https://user-images.githubusercontent.com/35939185/157105682-99742421-ef4b-4980-a391-ca8ce89e373e.png)

This's my log ANDROID studio:

D/Capacitor: Handling local request: http://localhost/2249-es2015.72114a937c7cb655f040.js
D/Capacitor: Handling local request: http://localhost/assets/icon/favicon.png
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 37102984, pluginId: CapacitorVideoPlayer, methodName: initPlayer
V/Capacitor: callback: 37102984, pluginId: CapacitorVideoPlayer, methodName: initPlayer, methodData: {"mode":"fullscreen","url":"XXXXX","playerId":"fullscreen","componentTag":"app-player"}
D/CapacitorVideoPlayer: **** isTV false ****
V/CapacitorVideoPlayer: display url:XXXXX
V/CapacitorVideoPlayer: display subtitle: 
V/CapacitorVideoPlayer: display language: 
V/CapacitorVideoPlayer: *** calculated videoPath: XXXXXX
V/CapacitorVideoPlayer: *** calculated subTitlePath: null
W/elendirecto.ap: Accessing hidden method Landroid/graphics/FontFamily;-><init>()V (light greylist, reflection)
W/elendirecto.ap: Accessing hidden method Landroid/graphics/FontFamily;->addFontFromAssetManager(Landroid/content/res/AssetManager;Ljava/lang/String;IZIII[Landroid/graphics/fonts/FontVariationAxis;)Z (light greylist, reflection)
W/elendirecto.ap: Accessing hidden method Landroid/graphics/FontFamily;->addFontFromBuffer(Ljava/nio/ByteBuffer;I[Landroid/graphics/fonts/FontVariationAxis;II)Z (light greylist, reflection)
W/elendirecto.ap: Accessing hidden method Landroid/graphics/FontFamily;->freeze()Z (light greylist, reflection)
W/elendirecto.ap: Accessing hidden method Landroid/graphics/FontFamily;->abortCreation()V (light greylist, reflection)
W/elendirecto.ap: Accessing hidden method Landroid/graphics/Typeface;->createFromFamiliesWithDefault([Landroid/graphics/FontFamily;Ljava/lang/String;II)Landroid/graphics/Typeface; (light greylist, reflection)
V/com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment: display url: XXXXXXX
V/com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment: display subtitle url: null
V/com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment: display isTV: false
V/com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment: display vType: mp4
W/elendirecto.ap: Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (light greylist, reflection)
I/ExoPlayerImpl: Init 9bbaed0 [ExoPlayerLib/2.11.4] [tissot_sprout, Mi A1, Xiaomi, 28]
W/MediaSessionCompat: Couldn't find a unique registered media button receiver in the given context.
W/MediaSessionCompat: Couldn't find a unique registered media button receiver in the given context.
W/elendirecto.ap: Accessing hidden field Landroid/view/WindowInsets;->CONSUMED:Landroid/view/WindowInsets; (light greylist, reflection)
W/elendirecto.ap: Accessing hidden method Landroid/view/View;->getViewRootImpl()Landroid/view/ViewRootImpl; (light greylist, reflection)
W/elendirecto.ap: Accessing hidden field Landroid/view/View$AttachInfo;->mVisibleInsets:Landroid/graphics/Rect; (light greylist, reflection)
W/elendirecto.ap: Accessing hidden field Landroid/view/ViewRootImpl;->mAttachInfo:Landroid/view/View$AttachInfo; (light greylist, reflection)
W/elendirecto.ap: Accessing hidden method Landroid/graphics/Insets;->of(IIII)Landroid/graphics/Insets; (light greylist, linking)
W/elendirecto.ap: Accessing hidden method Landroid/view/View;->transformMatrixToGlobal(Landroid/graphics/Matrix;)V (light greylist, linking)
I/Capacitor/Console: File: http://localhost/2249-es2015.72114a937c7cb655f040.js - Line 1 - Msg: res.result  true
D/Capacitor: Handling local request: http://localhost/assets/icon/favicon.png
W/VideoCapabilities: Unrecognized profile 4 for video/hevc
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
W/Utils: could not parse long range '175-174'
I/OMXClient: IOmx service obtained
D/SurfaceUtils: connecting to surface 0x7bb77f1010, reason connectToSurface
I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 2092033
D/SurfaceUtils: disconnecting from surface 0x7bb77f1010, reason connectToSurface(reconnect)
D/SurfaceUtils: connecting to surface 0x7bb77f1010, reason connectToSurface(reconnect)
I/ExtendedACodec: setupVideoDecoder()
I/ExtendedACodec: Decoder will be in frame by frame mode
D/SurfaceUtils: set up nativeWindow 0x7bb77f1010 for 1280x720, color 0x7fa30c06, rotation 0, usage 0x20002900
I/OMXClient: IOmx service obtained
I/ACodec: codec does not support config priority (err -2147483648)
I/ACodec: codec does not support config priority (err -2147483648)
W/ExtendedACodec: Failed to get extension for extradata parameter
D/SurfaceUtils: set up nativeWindow 0x7bb77f1010 for 1280x720, color 0x7fa30c06, rotation 0, usage 0x20002900
V/com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment: **** in ExoPlayer.STATE_READY firstReadyToPlay true
V/Capacitor/CapacitorVideoPlayerPlugin: Notifying listeners for event jeepCapVideoPlayerReady
D/Capacitor/CapacitorVideoPlayerPlugin: No listeners found for event jeepCapVideoPlayerReady
V/com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment: **** in ExoPlayer.STATE_READY firstReadyToPlay player.isPlayingtrue
V/com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment: **** in ExoPlayer.STATE_READY firstReadyToPlay false
V/com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment: **** in ExoPlayer.STATE_READY isPlaying true
V/com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment: **** in ExoPlayer.STATE_READY going to notify playerItemPlay 
V/Capacitor/CapacitorVideoPlayerPlugin: Notifying listeners for event jeepCapVideoPlayerPlay
D/Capacitor/CapacitorVideoPlayerPlugin: No listeners found for event jeepCapVideoPlayerPlay
V/com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment: **** in ExoPlayer.STATE_READY firstReadyToPlay false
V/com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment: **** in ExoPlayer.STATE_READY isPlaying false
V/com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment: **** in ExoPlayer.STATE_READY going to notify playerItemPause 
V/Capacitor/CapacitorVideoPlayerPlugin: Notifying listeners for event jeepCapVideoPlayerPause
D/Capacitor/CapacitorVideoPlayerPlugin: No listeners found for event jeepCapVideoPlayerPause
D/Capacitor: App paused
V/FA: Activity paused, time: 116001749
D/SurfaceUtils: connecting to surface 0x7b9b3df010, reason connectToSurface
I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 2092034
D/SurfaceUtils: disconnecting from surface 0x7b9b3df010, reason connectToSurface(reconnect)
D/SurfaceUtils: connecting to surface 0x7b9b3df010, reason connectToSurface(reconnect)
D/SurfaceUtils: set up nativeWindow 0x7b9b3df010 for 1280x720, color 0x7fa30c06, rotation 0, usage 0x20002900
D/SurfaceUtils: disconnecting from surface 0x7bb77f1010, reason disconnectFromSurface
D/Capacitor/AppPlugin: Firing change: false
V/Capacitor/AppPlugin: Notifying listeners for event appStateChange
D/Capacitor: App stopped
D/Capacitor: Saving instance state!
D/FA: Application going to the background
V/FA: Recording user engagement, ms: 90104
I/FA: Tag Manager is not found and thus will not be used
V/FA: Connecting to remote service
V/FA: Connection attempt already in progress
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 2
V/FA: Inactivity, disconnecting from the service
!

**Comment by jh-gh** [comment]
@juaala You could try using the Capacitor keep awake plugin https://github.com/capacitor-community/keep-awake
I have used that successfully with this plugin (though it might also be nice if the plugin supported this more directly).  In any case, if you call "keepAwake()" before playing a video ... and then "allowSleep()" after the video terminates (use the video plugin listeners to watch for this) ... this should do what you want.

**Comment by juaala** [comment]
Thanks @jh-gh I'll try. I saw de Flag that use Keep-awake and there is not in capacitor-video-player. The Flag is FLAG_KEEP_SCREEN_ON. Maybe we can integrate this flag into capacitor-video-player and keep screen on directly.

**Comment by juaala** [comment]
@jh-gh it works! Thank you. You safe my week.... Thank! @jepiqueau Could the FLAG_KEEP_SCREEN_ON be integrated?

**Comment by jepiqueau** [comment]
@jh-gh @juaala i do not really understand why this is happening on your device. This was fixed with the issue#33 where we add `android:keepScreenOn="true"` in the layout/bridge_layout_main.xml file of the plugin. I tested it in a old Note3 Samsung (API21) and on my S20FE (API31) on a video of 10:35 duration  and it is working without interruption and without screen turn off

**Comment by jepiqueau** [comment]
@jh-gh @juaala  anyhow i will add the flag FLAG_KEEP_SCREEN_ON  in the next release. Can you revert to me when tested

**Comment by jh-gh** [comment]
@jepiqueau I have tried this fix for keeping the screen on on Android.  I can confirm that before the fix, the screen would dim and then lock when the screen timeout is reached.  With the fix, the screen stays on while the video is playing even after the timeout has been reached.  Thanks for this useful improvement.

**Comment by jepiqueau** [comment]
@juaala thanks from @jh-gh test it seems working so i close the issue
