### ISSUE TITLE
Locking the screen on Android leaves the audio playing 

### ISSUE THREAD

**Issue by jh-gh** [jepiqueau/capacitor-video-player#80]
Tested with version 3.4.1-1 of the plugin and the angular starter app:

- Start fullscreen video
- Lock the screen

Expected: Audio pauses
Actual: Audio continues to play (and there is no built-in way to stop it on the lock screen)

On versions of this plugin before PIP support (e.g. 3.3.0-1 and 2.4.7), locking the screen while a video was playing would pause the video.  (Note that on iOS, locking the screen DOES pause the audio ... on current and past versions of the plugin).

Also, a couple of questions regarding the Android Manifest.  The documentation mentions that you should add the following to the activity tag in the manifest:

`  android:resizeableActivity="true"
    android:supportsPictureInPicture="true"`

However, the angular starter app has those attributes, but also 

`android:alwaysRetainTaskState="true"`

Is the "alwaysRetainTaskState" attribute required or recommended when using this plugin?

Also, if an app uses this plugin, but opts out of PIP support (by passing pipEnabled: false when calling initPlayer) does it still require these attributes on the Android manifest?  Or should they not be included.

Thanks.

**Comment by jepiqueau** [comment]
@jh-gh No this is the normal behavior when you lock the screen the audio continue to play in the background. That was remove when i have implemented the PIP so i put it back when i did a complete check. This give you the same behavior as on iOS with the audioSession.
if you opt out of PIP support you do not need to modify the Android Manifest

**Comment by jh-gh** [comment]
@jepiqueau I don't understand your comment above.  Are you saying that you have fixed this issue with release 3.4.1-3 and the audio should now pause when you lock the device on Android?  The changelog seems to suggest this (and the commit e915480 which references this issue).  

![image](https://user-images.githubusercontent.com/4483416/157317855-80f769f0-f7b5-441f-a200-cec3e07b58a9.png)

However, the behaviour on Android has not changed.  Locking the screen with a video playing on Android does NOT pause the video (testing in the Angular starter app).

By contrast, with plugin version 3.3.0-1 or 2.4.7 (before PIP), locking the screen on Android DOES pause the video.

Also, on all of those versions (2.4.7, 3.3.0-1, 3.4.1-3) on iOS ... locking the screen on iOS DOES pause the video.

I also tried playing videos in chrome and netflix on Android.  Locking the screen with a video playing in either of those apps DOES pause the audio.

**Comment by jh-gh** [comment]
@jepiqueau Note that this Android issue does not just occur when locking the device.  It also occurs any time the app goes into the background.  For example:

**User uses home button **

User starts playing a fullscreen video
User taps home button (app goes into the background but audio continues to play (should pause)

**User switches between apps with the app switcher **

User starts playing a fullscreen video
User uses the app switcher to switch to a different app (app goes into the background but audio continues to play (should pause)

This behaviour is only happening in these most recent version of the plugin (after 3.4.1-1)

**Comment by jepiqueau** [comment]
@jhgh i told you that this is the normal  behavior requested by some developers before i introduce the PIP mode. When you press on Home the vidéo audio continue to plan and when you reopen the app the video play again.

**Comment by jepiqueau** [comment]
@jh-gh if you do not want that i could add an option soundInBackground true/ false

**Comment by jepiqueau** [comment]
@jh-gh look at issue#13

**Comment by jh-gh** [comment]
@jepiqueau TLDR: **Yes, I like the idea of a soundInBackground boolean thanks.  That would enable me to get the same behaviour on both platforms that I currently get using the 2.4.7 version of the plugin.**

By the way, on iOS, I currently use the plugin WITHOUT adding the background modes.  I did it this way on purpose when using 2.4.7 ... as it was the only way that I could get a decent user experience.  I found that if I enabled the background modes (on 2.4.7 or 3.3.0-1) ... and then put the app in the background then resumed ... I would just get a blank screen ... with no video or controls (and the audio would continue to play).  For my purposes, it was better to just not enable the background mode ... and let the video/audio pause whenever the user locked the screen, put the app in the background, or switched apps.

Things are better if you add the background modes on 3.4.1-3 ... you no longer get this issue with the resuming the app with a blanks screen.  However, note that the audio does NOT continue when you lock the screen on iOS on 3.4.1-3 with the background modes enabled.  

Even if this all worked perfectly on iOS, I don't think I would use the background mode setting.  The issue for me is that if the user locks the device with a video playing and the audio continues ... there is no way for the user to stop it from playing from the lock screen (they need to fully unlock the device again).  This just doesn't seem right to me ... so I prefer not let the audio continue when the device is locked.

There are lots of permutations here and it can get a bit confusing.  I am attaching below some tests that I did to compare the behaviour among the different versions.

Thanks!

<img width="993" alt="image" src="https://user-images.githubusercontent.com/4483416/157554375-744fdca1-7b65-4154-99e0-260566b93424.png">

<img width="971" alt="image" src="https://user-images.githubusercontent.com/4483416/157554405-43b3f991-de53-48cd-a9b8-a27998cb2a93.png">

<img width="982" alt="image" src="https://user-images.githubusercontent.com/4483416/157554459-a5ad9f60-4a92-4125-a1c6-e07ffa283a33.png">

**Comment by jepiqueau** [comment]
@jh-gh well it seems that you do not want to have at all the backround mode so the soundInBackground is then the option. I will go for this when i have a bit free time. Anyhow thanks for all your comments

**Comment by jepiqueau** [comment]
@jh-gh in release 3.4.1 à parameter bkmodeEnabled has been added . The default value is true. The iOS part has now the  same behavior than the Android part. Hope this will making you closing the issue . Enjoy

**Comment by jh-gh** [comment]
@jepiqueau Thanks for adding the bkmodeEnabled parameter.  However, unfortunately release 3.4.1 seems to have issues.

For my use case, I would like to set pipEnabled=false, bkmodeEnabled=false (and not enable the background mode in iOS settings).

However, with these settings in place, when you play a video on iOS, **you get no audio at all.**

Also, there are issues on iOS generally in 3.4.1 when you are playing the video full screen ... and then tap and hold the bottom of the screen and start to swipe up to switch apps.  When you do this, the video disappears (the audio and subtitles keep playing).  You can pause/play and the audio and sub-titles will do the right thing ... but the video never reappears.  This behaviour occurs even with the default settings (pipEnabled=true,bkmodeEnabled=true).  It's a bit different on the simulator (iphone 13 15.2) but still broken there as the video seems to freeze ... audio/subtitles continue to play.

On Android, the bkModeEnabled=true parameter does work (audio stops when you pause the app, switch apps, or lock the screen).  However, when you resume the app (either by tapping home screen icon, using the app switcher, or unlocking the screen) the video resumes playing automatically.   In previous versions of the plugin (2.4.7 and 3.3.0-1) resuming the app on Android would NOT automatically start the video again.

In general, I feel that resuming the app should never automatically resume the video on either platform (or at least it shouldn't do this if pip is not being used).  This is better left to the user to tap play.  They may not be expecting the video (and audio) to start when they simply unlock the screen for example.  With 3.4.1 on Android, even if the user explicitly pauses the video before switching out of the app (either by locking the screen, tapping home, or using the app switcher) ... the plugin resumes the video whenever the app gets resumed.  As a user I would find this behaviour to be annoying.  However, with the plugin as it stands, I can't see any way to work around it cleanly.  The best I could do would be to programatically pause the video after the app resumes ... but I would need to wait until I received an event indicating that the player had started playing ... and there may be a brief sound before the video would stop.

So once again, ideally, (if using pipEnabled=false and bkmodeEnabled=false) I think the plugin should behave as follows on both platforms:
- Whenever the user pauses the app (locks the screen, taps home, or switches to another app), the video and audio should pause
- Whenever the user resumes the app (unlocks the screen, taps launch icon, or switches to the app), the full screen video player should be displayed in a paused state at the point at which the user left the app

I appreciate all your great support on this plugin.  Note that for me at least, this is not urgent at the moment.  For now, I can continue to use version 3.3.0-1 which behaves almost exactly as I summarised just above (the only exception being that on iOS when the app resumes, it DOES resume automatically if the video had been playing when the app was paused.  This is not ideal in my opinion ... but I can live with it.  Thanks.

**Comment by jepiqueau** [comment]
@jh-gh thanks for all this tough testing. I will have a look if i can reproduce it. My problem is i do not have an iPhone device so it is quite hard to test as you do.
