### ISSUE TITLE
landscape video

### ISSUE THREAD

**Issue by lestercastillo** [jepiqueau/capacitor-video-player#81]
it is possible auto rotate video once it was clicked ?

**Comment by jepiqueau** [comment]
@lestercastillo you can rotate the screen  and the video will rotate. To rotate the video without rotating the screen you cannot do it.

**Comment by lestercastillo** [comment]
> @lestercastillo you can rotate the screen and the video will rotate. To rotate the video without rotating the screen you cannot do it.

thanks man <3

**Comment by jepiqueau** [comment]
@lestercastillo  Can we close this issue
