### ISSUE TITLE
XCode 13.3 – Segmentation fault: 11

### ISSUE THREAD

**Issue by danielreiser** [jepiqueau/capacitor-video-player#82]
Thanks for creating this amazing lib!

Unfortunately after xcode quietly upgraded to 13.3, when trying to build a release version of my app I get 
Xcode 13.2.1 still works as expected.

`error: Segmentation fault: 11 (in target 'CapacitorVideoPlayer' from project 'Pods')`

Tried everything from doing a clean build, removing derived data etc.

I am using the latest version of
- capacitor-video-player 3.4.1
- xcode 13.3
- ios 15.4
- deploymenttarget target is 15.0

**Comment by jepiqueau** [comment]
@danielreiser it should be from your side i have the same versions than you and testing on a simulator iPhone 13 Pro Max and it is working

**Comment by danielreiser** [comment]
thanks for the feedback. strange. I don't have changed anything but use the latest xcode. with the previous version it works as expected 🤷‍♂️

**Comment by jepiqueau** [comment]
@danielreiser did you progress on this? May be you need to remove the ios folderfrom your app and add it again

**Comment by joannadal** [comment]
Hi there!

Same issue here. Using Xcode 13.3 trying to archive the .ipa file. 

Could you anyone help me with this?

Thanks!

**Comment by jepiqueau** [comment]
@joannadal i cannot check this as i am not enroll to the apple developer program.

**Comment by fathanyr** [comment]
> Hi there!
> 
> Same issue here. Using Xcode 13.3 trying to archive the .ipa file.
> 
> Could anyone help me with this?
> 
> Thanks!

Same here, could anyone ?

![image](https://user-images.githubusercontent.com/48428195/160325217-d4ae7fc4-bbca-466d-8be6-ffa36dee10a5.png)

**Comment by mueslirieger** [comment]
I'm getting the same error as @fathanyr but I found the following solution for it in the Apple dev forums.
Changing Line 40 in *CapacitorVideoPlayPlugin.swift* from `if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiom.pad),` to `if (UIDevice.current.userInterfaceIdiom == UIUserInterfaceIdiom.pad),` did the trick for me.

**Comment by jepiqueau** [comment]
@mueslirieger thanks for this, can you make a PR i will merge it in the next release. If others having the same issue can test and confirm that it is works it would be appreciate.

**Comment by jepiqueau** [comment]
@danielreiser @joannadal @mueslirieger  Sorry guys i did not hear anything from you. Can you confirm that what is proposed by @mueslirieger  works. In that case , i will publish a new release

**Comment by mueslirieger** [comment]
@jepiqueau Sorry for the late answer. Of course, I will make open a PR in the course of the day.

**Comment by jepiqueau** [comment]
@mueslirieger ok

**Comment by jepiqueau** [comment]
@mueslirieger Thank you for spending time to fix this issue. The PR has been merged and part of the new release 3.4.2-2

**Comment by danielreiser** [comment]
> @danielreiser @joannadal @mueslirieger Sorry guys i did not hear anything from you. Can you confirm that what is proposed by @mueslirieger works. In that case , i will publish a new release

Sorry for not responding earlier! Thank you very much!
