### ISSUE TITLE
Android application crashes sometimes on playerEnd/playerExit.

### ISSUE THREAD

**Issue by yelhouti** [jepiqueau/capacitor-video-player#86]
The issue seems to come from the notificationCenter.

Since synchronized uses a re entrant lock, postNotification (for playerEnd, playerExit) calls removeAllNotifications the iteration breaks with ConcurrentModificationException.

Using a non re entrant lock (example Semaphore) doesn't solve the problem, since everything is called on the UIThread.

To fix this, iterating on the list of notifications should be done differently so that even if the first run removes them all. They keep executing before disappearing.

**Comment by jepiqueau** [comment]
@yelhouti thanks for this can you make a PR to fix this i will look at it and merge it

**Comment by yelhouti** [comment]
@jepiqueau here you go

**Comment by jepiqueau** [comment]
@yelhouti @mamane10 Thanks for your work. Now published in 3.4.2
