### ISSUE TITLE
[Web] video still play after close it

### ISSUE THREAD

**Issue by raykin** [jepiqueau/capacitor-video-player#88]
Close video when loading icon is circling can close video UI but video is still playing on background because audio is still playing after loading finished. Bug only exists for PWA/Web.

**Comment by jepiqueau** [comment]
@raykin thanksfor using the plugin. can you share a repro app on github demonstrating the issue

**Comment by raykin** [comment]
@jepiqueau okay. I'm not free on repro it right now. I can try it on this weekend.

**Comment by raykin** [comment]
No such bug in my recent tests. Strange because related code didn't change at all but I can't reproduce the bug. So it probably somewhere fixed by other dependencies.
