### ISSUE TITLE
not supporting androidx 

### ISSUE THREAD

**Issue by armanhadifatah** [jepiqueau/capacitor-video-player#9]
I use capacitor 2.0.0 and on android it gives me error and i think it is because not supporting androidx

**Comment by jepiqueau** [comment]
@armanhadifatah Thanks for using the plugin, yes you right, i have to move it to capacitor 2.0.

**Comment by jepiqueau** [comment]
@armanhadifatah  This is done in the release 2.0.1-1 of the plugin. Enjoy

**Comment by jepiqueau** [comment]
@armanhadifatah you can close the issue after testing of the new release

**Comment by armanhadifatah** [comment]
Thank you very much 
I updated plugin but now there is no plugin class when i want to add it 

`add(CapacitorVideoPlayer.class);`

`can not resolve symbol 'CapacitorVideoPlayer'`

There is no plugin folder in the project

**Comment by jepiqueau** [comment]
@armanhadifatah Have you migrate your app to androidX see the doc of the ionic capacitor team
at https://capacitor.ionicframework.com/docs/android/updating/ , i did that and it work nicely;

make sure that in your mainActivity.java file you import the plugin
```
import com.jeep.plugin.capacitor.CapacitorVideoPlayer;
``` 
in android studio
clean the project
sync project with gradle files
build the project
and run it
if this procedure doesn't work, save your project on github and i can have a look

**Comment by armanhadifatah** [comment]
Great now it is working 

But if you just add 

```
 <ProgressBar
        android:id="@+id/indeterminateBar"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="@+id/videoViewId"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
```

in `activity_videoplayer.xml`

and add `Pbar = (ProgressBar)findViewById(R.id.indeterminateBar);`
in `VideoPlayerActivity`

and inside ` videoView.setOnPreparedListener`

just hide it `Pbar.setVisibility(View.GONE);`

**Comment by jepiqueau** [comment]
@armanhadifatah I am pleased 😀 to hear that it works. That a good suggestion, i will do it in the next release.

**Comment by jepiqueau** [comment]
@armanhadifatah Progress Bar implemented Enjoy!
