### ISSUE TITLE
Double player on mobile browser

### ISSUE THREAD

**Issue by DmitryBara** [jepiqueau/capacitor-video-player#93]
**Platform**: IOS mobile Safari

**Current Behavior**: When I do `.initPlayer()` firstly I see web player hls.js where I press play button and get transferred to native mode.

**Expected Behavior**: Native player initialized by default. Without intermediate layer hls.js video player.

Link with demonstration of bug:
https://drive.google.com/file/d/1TiRKlcmWMhRzWTecc2rXllwJ-sXb1Pv9/view?usp=sharing

**Comment by DmitryBara** [comment]
Anybody have suggestions about this issue? Maybe you could give a hint how to fix it and where (probably in library) to search a bug?

**Comment by jepiqueau** [comment]
@DmitryBara Can you share your code i never saw this behavior

**Comment by DmitryBara** [comment]
@jepiqueau 

My function for player initialization
` ``
const playVideo = () => {
    await CapacitorVideoPlayer.initPlayer({
      mode: "fullscreen",
      url: urls.content.high,
      playerId: "playerId-main",
      componentTag: "div",
    });

    await CapacitorVideoPlayer.play({ playerId: "playerId-main" });
}
```

And in JSX body I have:
`<div id="playerId-main">`


Dependencies:
```
"capacitor-video-player": "^3.4.2",
"@ionic/react": "^6.0.0",
"@ionic/react-router": "^6.0.0",
```

**Comment by jepiqueau** [comment]
@DmitryBara Have you move to capacitor 4 and the latest release of  `capacitor-video-player` Have you still have the issue. I will close the issue feel free to re-open it if necessary
