### ISSUE TITLE
fullscreen mode

### ISSUE THREAD

**Issue by amirheydari9** [jepiqueau/capacitor-video-player#95]
Uncaught (in promise) TypeError: Fullscreen request denied

i write methode to paly video in fullscreen

async play(video: string) {
    // Get the video as base64 data
    const realUrl = await this.videoService.getVideoUrl(video);

    // Show the player fullscreen
    await this.videoPlayer.initPlayer({
      mode: 'fullscreen',
      url: realUrl,
      playerId: 'fullscreen',
      componentTag: 'app-home'
    });
  }

**Comment by jepiqueau** [comment]
@amirheydari9 on which platform

**Comment by jepiqueau** [comment]
@amirheydari9 the player is not playing base64 videos.
