### ISSUE TITLE
Can't play video files from Internal folder.

### ISSUE THREAD

**Issue by luislopezlopez** [jepiqueau/capacitor-video-player#96]
When I play a video from internal folder (file:///) I receive "filePath not implemented" when I initialize the player. But everything works fine when I play a video from a http url.

I don't know if i am miss understanding the documentation.

**Version:**
Capacitor video player : 3.4.2

**Platform:** 
iOS

**Comment by luislopezlopez** [comment]
Sorry I tested on a real device and everything works perfect.

**Comment by jepiqueau** [comment]
@luislopezlopez on which platform

**Comment by jepiqueau** [comment]
@luislopezlopez OK 👌 so i close it
