### ISSUE TITLE
capacitor-video-player vs `<video>`

### ISSUE THREAD

**Issue by matzar** [jepiqueau/capacitor-video-player#97]
Genuine question here to which I'd love to know an answer to - what are the advantages of using capacitor-video-player over HTML5's `<video>` element? 

I've used `<video>` element in my Angular app and it translated without a problem to iOS and Android with capacitor.

**Comment by jepiqueau** [comment]
@matzar by doing so you are using the Web browser player and not directly the native players.

**Comment by matzar** [comment]
@jepiqueau how is capacitor-video-player using the native players?

I thought is was also creating a `<video>` HTML element
https://github.com/jepiqueau/capacitor-video-player/blob/596334d9c8540299136ac8911264a2998ae4bc38/src/web-utils/videoplayer.ts#L127

but maybe this is doing something else?

**Comment by jepiqueau** [comment]
@matzar for the Web the plugin uses HTML vidéo élément. For the native apps the plugin uses directly the native player. Ie for Android it is using an Exoplayer and for iOS the Apple player

**Comment by matzar** [comment]
@jepiqueau great, that's what I wanted to know - thanks!
