### ISSUE TITLE
Hide controls and loading indicator

### ISSUE THREAD

**Issue by RRGT19** [jepiqueau/capacitor-video-player#98]
Hi,

1. There is a way to hide/not show the video controls?
2. There is a way to hide/not show the loading indicator that appears at the beginning?

I'm trying to do a video splash screen. After my app is loaded, I hide the splash and I play a short video. The loading indicator and the controls gives a weird impression.

**Comment by jepiqueau** [comment]
@RRGT19 thanks for using the plugin. There is no option available to hide the video controls and the loading indicator. Which platform are you using ?

**Comment by RRGT19** [comment]
@jepiqueau Hi, thanks for your reply. We are using just **Android** and **iOS**. The purpose is to do a fake splash screen reproducing a short video after the app has loaded. Would be awesome to be able to hide the controls and the loading indicator if possible.

**Comment by jepiqueau** [comment]
@RRGT19 in release 4.8.0  a showControls boolean has been added to the options. Hope this is not too late for you. I close the issue
