### ISSUE TITLE
Any possibility to use headers in the request?

### ISSUE THREAD

**Issue by PhantomPainX** [jepiqueau/capacitor-video-player#99]
I'm currently using a fork from the Cordova streaming video plugin where I added the support for custom headers, and I'd like to update to this plugin since I'm using capacitor now instead of Cordova.

Any possibility of adding this feature, or if it is already added, how to use it?

**Comment by jepiqueau** [comment]
@PhantomPainX thanks for looking at the plugin. What do you mean by custom headers

**Comment by PhantomPainX** [comment]
> @PhantomPainX thanks for looking at the plugin. What do you mean by custom headers

Hey, thanks for answer. For example I want to play an external video that needs an Authorization token or a Referer of the same domain. Without sending those headers in the request, the video won't play, because the video server end will block it.

**Comment by jepiqueau** [comment]
@PhantomPainX Understand your request. No idea how to do that and also to test it as i do not have access to a video server requesting autorization token. May be you can look at it and make a PR when tested.

**Comment by PhantomPainX** [comment]
> @PhantomPainX Understand your request. No idea how to do that and also to test it as i do not have access to a video server requesting autorization token. May be you can look at it and make a PR when tested.

Yeah, I will probably do it in the same way as I did with the cordova one. Thanks :)

**Comment by jepiqueau** [comment]
@PhantomPainX let me know about your progress. I will merge the PR

**Comment by PhantomPainX** [comment]
> @PhantomPainX let me know about your progress. I will merge the PR

I think I did it for iOS, tested in simulator and it works well, I can pass headers in the request

**Comment by jepiqueau** [comment]
@PhantomPainX can you do it also for Android and web

**Comment by PhantomPainX** [comment]
> @PhantomPainX can you do it also for Android and web

Web I don't think, I'm trying to do it in Android but I don't understand how to pass headers to ExoPlayer :(

**Comment by PhantomPainX** [comment]
Ok, I managed to do it in Android too. I'm going to upload the PR in some hours.
